# generated by datamodel-codegen:
#   filename:  ability.yaml
#   timestamp: 2025-11-27T09:21:11+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Ability(RESTPayload):
    """An ability triggered by a character or vehicle.

    Abilities in the API are more generic than the in-game abilities
    and also cover other mechanics such as scopes and consumables.

    The generic fields `paramX` and `stringX` are documented in the
    the corresponding `ability_type` entry."""

    ability_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique identifier of the ability."""
    ability_type_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'ps2/ability_type'},
    )
    """Unique identifier of the ability's type."""
    distance_max: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Maximum cast range of the ability for targeted abilities, such as
    the Nano-Repair Kit (aka. repair gun)."""
    expire_msec: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Duration of the ability in milliseconds."""
    first_use_delay_msec: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Initial delay before the ability can be used for the first time
    in milliseconds."""
    flag_toggle: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether the ability is toggled."""
    next_use_delay_msec: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Reuse cooldown for toggled abilities (mostly cloaks) in
    milliseconds"""
    param1: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param10: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param11: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param12: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param13: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param14: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param2: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param3: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param4: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param5: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param6: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param7: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param8: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    param9: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/ability_type` for details."""
    radius_max: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Effect radius of the ability, such as the Nano Regen Device (aka.
    AoE heal)."""
    resource_cost_per_msec: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Cost per millisecond for keeping the ability active."""
    resource_first_cost: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Initial cost for activating the ability."""
    resource_type_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'ps2/resource_type'},
    )
    """Unique identifier of the resource type consumed by the ability."""
    reuse_delay_msec: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Ability cooldown in milliseconds."""
    string1: str | None = None
    """Generic string field. See the corresponding `ps2/ability_type`
    for details."""
    string2: str | None = None
    """Generic string field. See the corresponding `ps2/ability_type`
    for details."""
    string3: str | None = None
    """Generic string field. See the corresponding `ps2/ability_type`
    for details."""
    string4: str | None = None
    """Generic string field. See the corresponding `ps2/ability_type`
    for details."""
