# generated by datamodel-codegen:
#   filename:  achievement.yaml
#   timestamp: 2025-11-27T09:21:15+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Achievement(RESTPayload):
    """Endpoint for weapon medals and service ribbons.

    There is no "achievement type" collection or field, but they can
    be grouped by the `repeatable` field, which is only true for
    service ribbons."""

    achievement_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    description: LocalizedString | None = None
    """Description of the achievement."""
    image_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the image associated with this achievement."""
    image_path: str | None = None
    """Path to the image associated with this achievement."""
    image_set_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the image set associated with this achievement."""
    item_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """ID of the item associated with this achievement. Can be used to
    associate weapons with their medals/ribbon."""
    name: LocalizedString | None = None
    """Name of the achievement."""
    objective_group_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """ID of the objective group counting towards this achievement."""
    repeatable: bool | None = Field(None, json_schema_extra={'x-cast-to': 'bool'})
    """Whether this achievement can be gained more than once. True for
    ribbons, false for medals."""
    reward_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the reward granted upon completion of this achievement."""
