# generated by datamodel-codegen:
#   filename:  armor_info.yaml
#   timestamp: 2025-11-27T09:21:20+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ArmorInfo(RESTPayload):
    """description: A set of armor values for each armor facing angle on
    a vehicle."""

    armor_amount: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Flat damage reduction applied to incoming damage. Only used in
    the tutorial to make target dummies invincible."""
    armor_facing_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """ID of the armor facing direction."""
    armor_info_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    armor_percent: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Damage reduction in percent. Negative values increase damage
    taken."""
    description: str | None = None
    """Description of the armor info entry."""
