# generated by datamodel-codegen:
#   filename:  armor_facing.yaml
#   timestamp: 2025-11-27T09:21:18+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ArmorFacing(RESTPayload):
    """Enumerates the armor facing angles used for directional damage
    reduction on vehicles."""

    armor_facing_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    description: str
    """Description of the armor facing direction."""
