# generated by datamodel-codegen:
#   filename:  characters_weapon_stat_by_faction.yaml
#   timestamp: 2025-11-27T09:22:15+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersWeaponStatByFactionCore(RESTPayload):
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The ID of the item."""
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    stat_name: str = Field(
        ..., json_schema_extra={'x-reference-to': 'characters_stat.stat_name'}
    )
    """The name of the stat being recorded."""
    value_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat for the NC faction."""
    value_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat for the TR faction."""
    value_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat for the VS faction."""
    vehicle_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """The ID of the vehicle."""


class CharactersWeaponStatByFaction(CharactersWeaponStatByFactionCore):
    """Faction-specific weapon statistics endpoint containing combat-
    focussed stats such as kills,
    deaths, headshots and damage dealt/taken.

    - `stat_name` lists the name of the stat
    - `item_id` identifies the item for the weapon. Note that this
    value can be zero, in that
      case it serves as a catch-all for all weapons for the given
    `vehicle_id`.
    - `vehicle_id` the vehicle on which the weapon is available."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The ID of the character."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The ID of the item."""
    stat_name: str = Field(
        ..., json_schema_extra={'x-reference-to': 'characters_stat.stat_name'}
    )
    """The name of the stat being recorded."""
