# generated by datamodel-codegen:
#   filename:  characters_achievement.yaml
#   timestamp: 2025-11-27T09:21:30+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersAchievement(RESTPayload):
    """List the achievement progress for a character."""

    achievement_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'achievement.achievement_id',
        },
    )
    """Unique ID of the achievement being returned."""
    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the achievement list is being returned."""
    earned_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of times the achievement has been earned. Only exceeds 1
    for ribbons."""
    finish: str | None = None
    """UTC timestamp of when this achievement was completed. Remains at
    zero for repeatable achievements."""
    finish_date: str | None = None
    """Human-readable version of `finish`."""
    last_save: str | None = None
    """UTC timestamp of when the underlying table was updated."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    start: str | None = None
    """UTC timestamp of when progression towards this achievement
    started. For repeatable achievements, this marks the last time
    the achievement was gained."""
    start_date: str | None = None
    """Human-readable version of `start`."""
