# generated by datamodel-codegen:
#   filename:  characters_directive_tier.yaml
#   timestamp: 2025-11-27T09:21:41+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersDirectiveTier(RESTPayload):
    """Directive tier completion information for a character."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the directive tier list is being returned."""
    completion_time: str | None = None
    """UTC timestamp of when the directive tier was completed. Zero if
    not completed."""
    completion_time_date: str | None = None
    """Human-readable version of `completion_time`."""
    directive_tier_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tier.directive_tier_id',
        },
    )
    """ID of the directive tier."""
    directive_tree_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tree.directive_tree_id',
        },
    )
    """ID of the directive tree containing the directive."""
