# generated by datamodel-codegen:
#   filename:  characters_world.yaml
#   timestamp: 2025-11-27T09:22:17+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersWorld(RESTPayload):
    """Query the game server a character is on."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the world is being returned."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The `ps2/world` of the character."""
