# generated by datamodel-codegen:
#   filename:  characters_leaderboard.yaml
#   timestamp: 2025-11-27T09:21:57+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersLeaderboard(RESTPayload):
    """Query the leaderboard for a character. Note that only the top
    10'000 players for a given statistic are tracked in the
    leaderboard; many characters will not have an entry in this
    collection.

    The `limit` key inserted into the response indicates the number
    of requested entries when passing multiple character IDs.
    Comparison with `returned` may be used to determine whether any
    characters were skipped due to not being in the leaderboard."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The ID of the character."""
    rank: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """The rank of the character for the given statistic."""
    value: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given statistic."""
