# generated by datamodel-codegen:
#   filename:  characters_directive_objective.yaml
#   timestamp: 2025-11-27T09:21:39+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersDirectiveObjective(RESTPayload):
    """Current progress of a character within a directive.

    The current value of the directive progress can be found in the
    `state_data` field of this endpoint. The corresponding target
    value is found in the corresponding `objective`, usually in the
    `param1` field."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the directive objective status is being
    returned."""
    directive_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive.directive_id',
        },
    )
    """ID of the directive for which objective status is returned."""
    objective_group_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'objective_group.objective_group_id',
        },
    )
    """ID of the objective group for which status is returned."""
    objective_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'objective.objective_id',
        },
    )
    """ID of the objective for which status is returned."""
    state_data: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Progress of the character of the objective. This is the "current"
    value of the progress. The total can be found in the
    corresponding `objective`, usually under `param1`."""
    status: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Unknown."""
