# generated by datamodel-codegen:
#   filename:  characters_item.yaml
#   timestamp: 2025-11-27T09:21:54+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersItemCore(RESTPayload):
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""


class CharactersItem(CharactersItemCore):
    """Query the items of a character. Note that this collection no
    longer lists account-wide item unlocks as this served as a
    fingerprint to identify players across multiple characters."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character side of the relationship."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""
