# generated by datamodel-codegen:
#   filename:  characters_online_status.yaml
#   timestamp: 2025-11-27T09:22:00+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersOnlineStatus(RESTPayload):
    """Query the online status of a character"""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the online status is being returned."""
    online_status: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Whether the character is currently online. Offline players will
    return 0, otherwise the value will be the `world_id` of the
    `ps2/world` they are online on."""
