# generated by datamodel-codegen:
#   filename:  characters_stat_by_faction.yaml
#   timestamp: 2025-11-27T09:22:07+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersStatByFactionCore(RESTPayload):
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class for which stats are being returne."""
    stat_name: str
    """Name of the stat being returned."""
    value_daily_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours (NC)."""
    value_daily_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours (TR)."""
    value_daily_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours (VS)."""
    value_forever_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat (NC)."""
    value_forever_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat (TR)."""
    value_forever_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat (VS)."""
    value_monthly_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days (NC)."""
    value_monthly_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days (TR)."""
    value_monthly_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days (VS)."""
    value_one_life_max_nc: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life (NC)."""
    value_one_life_max_tr: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life (TR)."""
    value_one_life_max_vs: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life (VS)."""
    value_weekly_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days (NC)."""
    value_weekly_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days (TR)."""
    value_weekly_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days (VS)."""


class CharactersStatByFaction(CharactersStatByFactionCore):
    """Faction-specific statistics endpoint. Useful for determining
    faction bias or kill spread.

    - `stat_name` lists the name of the stat
    - `profile` represents the class, with a value of 0 denoting a
    character-wide value

    All `value_*` fields are provided per-faction. Note that the
    value for the own faction is
    often blanked: `value_nc` of the stat `kills` cannot be used to
    enumerate an NC character's
    team kills, for example."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the stats are being returned."""
    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class for which stats are being returne."""
    stat_name: str
    """Name of the stat being returned."""
