# generated by datamodel-codegen:
#   filename:  character_name.yaml
#   timestamp: 2025-11-27T09:21:27+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Name(RESTPayload):
    """Name of the character. Use the `first_lower` field for faster
    case-insensitive searches without needing to set `c:case=false`."""

    first: str | None = None
    first_lower: str | None = None


class CharacterName(RESTPayload):
    """Optimized, low-bandwidth endpoint for character name resolution."""

    character_id: int = Field(..., json_schema_extra={'x-cast-to': 'int64'})
    """Unique ID of the collection."""
    name: Name
    """Name of the character. Use the `first_lower` field for faster
    case-insensitive searches without needing to set `c:case=false`."""
