# generated by datamodel-codegen:
#   filename:  characters_directive_tree.yaml
#   timestamp: 2025-11-27T09:21:44+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersDirectiveTree(RESTPayload):
    """Directive tree completion information for a character."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the directive tree list is being returned."""
    completion_time: str | None = None
    """UTC timestamp of when the directive tree was completed. Zero if
    not completed."""
    completion_time_date: str | None = None
    """Human-readable version of `completion_time`."""
    current_directive_tier_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tier.directive_tier_id',
        },
    )
    """Unique ID of the directive tier the character is currently on."""
    current_level: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Defunct field. Always returns zero."""
    directive_tree_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tree.directive_tree_id',
        },
    )
    """ID of the directive tree."""
