# generated by datamodel-codegen:
#   filename:  characters_directive.yaml
#   timestamp: 2025-11-27T09:21:36+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersDirective(RESTPayload):
    """Directive completion information for a character.

    Note that this also lists entries for incomplete directives; use
    the `completion_time` field to determine whether a directive has
    been completed."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the directive list is being returned."""
    completion_time: str | None = None
    """UTC timestamp of when the directive was completed. Zero if not
    completed."""
    completion_time_date: str | None = None
    """Human-readable version of `completion_time`."""
    directive_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive.directive_id',
        },
    )
    """ID of the directive."""
    directive_tree_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tree.directive_tree_id',
        },
    )
    """ID of the directive tree containing the directive."""
