# generated by datamodel-codegen:
#   filename:  characters_event_grouped.yaml
#   timestamp: 2025-11-27T09:21:49+00:00

from enum import Enum

from auraxium.models.base import RESTPayload
from pydantic import Field


class TableType(Enum):
    """
    Type of event being returned.
    """

    KILL = 'KILL'
    DEATH = 'DEATH'


class CharactersEventGrouped(RESTPayload):
    """Return character vs. character statistics.

    Allows calculating player vs. player KDR."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Other character for which the event list is being returned."""
    count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of matching events."""
    table_type: TableType
    """Type of event being returned."""
