# generated by datamodel-codegen:
#   filename:  characters_currency.yaml
#   timestamp: 2025-11-27T09:21:33+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersCurrencyCore(RESTPayload):
    currency_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'currency.currency_id',
        },
    )
    """Unique ID of the currency being returned."""
    currency_name: str | None = None
    """Internal name of the currency being returned."""
    prestige_currency: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Number of A.S.P. tokens available to the character."""
    quantity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Amount of currency the character owns."""


class CharactersCurrency(CharactersCurrencyCore):
    """Lists the currencies owned by a character.

    Note that this table has been inconsistent since the introduction
    of the A.S.P. system: in addition to the currency value
    (Nanites), an extra `prestige_currency` key has been added,
    rather than being its own currency."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the currency list is being returned."""
    currency_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'currency.currency_id',
        },
    )
    """Unique ID of the currency being returned."""
