# generated by datamodel-codegen:
#   filename:  characters_stat_history.yaml
#   timestamp: 2025-11-27T09:22:10+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersStatCore(RESTPayload):
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    profile_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class for which stats are being returne."""
    stat_name: str
    """Name of the stat being returned."""
    value_daily: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours."""
    value_forever: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat."""
    value_monthly: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days."""
    value_one_life_max: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life."""
    value_weekly: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days."""


class CharactersStatHistory(CharactersStatCore):
    """Statistics endpoint for historical character stats. In addition
    to the `all_time` and
    `one_life_max` keys, values are also provided for the last 31
    days (`day`), 12 months
    (`month`), or 13 weeks (`week`).

    - `stat_name` lists the name of the stat
    - `profile` represents the class, with a value of 0 denoting a
    character-wide value"""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the stats are being returned."""
    stat_name: str
    """Name of the stat being returned."""
