# generated by datamodel-codegen:
#   filename:  characters_weapon_stat.yaml
#   timestamp: 2025-11-27T09:22:12+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersWeaponStatCore(RESTPayload):
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The ID of the item."""
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    stat_name: str = Field(
        ..., json_schema_extra={'x-reference-to': 'characters_stat.stat_name'}
    )
    """The name of the stat being recorded."""
    value: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat."""
    vehicle_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """The ID of the vehicle."""


class CharactersWeaponStat(CharactersWeaponStatCore):
    """Weapon statistics endpoint containing generic values such as
    playtime or score while
    wielding. The most common use is calculating the accuracy of a
    player with a given weapon
    by dividing `weapon_hit_count` by `weapon_fire_count`.

    - `stat_name` lists the name of the stat
    - `item_id` identifies the item for the weapon. Note that this
    value can be zero, in that
      case it serves as a catch-all for all weapons for the given
    `vehicle_id`.
    - `vehicle_id` the vehicle on which the weapon is available."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The ID of the character."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The ID of the item."""
    stat_name: str = Field(
        ..., json_schema_extra={'x-reference-to': 'characters_stat.stat_name'}
    )
    """The name of the stat being recorded."""
