# generated by datamodel-codegen:
#   filename:  character.yaml
#   timestamp: 2025-11-27T09:21:23+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class BattleRank(RESTPayload):
    """Sub-object providing battle rank information."""

    percent_to_next: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Progress to the next level-up."""
    value: str | None = None
    """Current battle rank. Note that due to the A.S.P. prestige system,
    this is no longer sufficient to express player level. Always
    check `prestige_level` as well."""


class Certs(RESTPayload):
    """Sub-object providing certification point information."""

    available_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Current certification point balance."""
    earned_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Certifications earned through experience gain."""
    gifted_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Certifications gifted through in-game events or refunds."""
    percent_to_next: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Progress to earning the next certification point (every 250 exp)."""
    spent_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Certifications points spent on skills and implant bundles."""


class DailyRibbon(RESTPayload):
    """Sub-object for daily ribbon bonuses. Note that ribbon bonuses
    have been disabled, rendering this object useless. It is
    recommended to treat is as optional in client code in case it
    ever gets removed from the response object."""

    count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of daily ribbon bonuses available for collection."""
    date: str | None = None
    """Human-readable version of `time`."""
    time: str | None = None
    """Next time a daily ribbon bonus will be granted."""


class Name(RESTPayload):
    """Name of the character. Use the `first_lower` field for faster
    case-insensitive searches without needing to set `c:case=false`."""

    first: str | None = None
    first_lower: str | None = None


class Times(RESTPayload):
    """Sub-object providing login time and playtime information."""

    creation: str | None = None
    """Character creation timestamp in UTC."""
    creation_date: str | None = None
    """Human-readable version of `creation`."""
    last_login: str | None = None
    """Last time the character logged in. Together with `last_save`,
    this can be used to construct the duration of the last play
    session of the character."""
    last_login_date: str | None = None
    """Human-readable version of `last_login`."""
    last_save: str | None = None
    """Last time the character info was updated. This generally
    corresponds to the last time the character logged off. For this
    reason, characters are generally not available on the API during
    their first play session."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    login_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of individual logins by the character."""
    minutes_played: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Total playtime in minutes."""


class Character(RESTPayload):
    """Main `character` collection holding player data.

    This collection is randomly distributed across 20 different
    databases, causing some unusual behaviour when filtering. For
    example, the `c:distinct` parameter will fetch the distinct
    values for each database and aggregate them in the response,
    resulting in duplicate entries.

    In addition to the commonly-used parameters provided, this
    endpoint may be queried by any of its fields, including sub-keys
    like `times.creation`."""

    battle_rank: BattleRank | None = None
    """Sub-object providing battle rank information."""
    certs: Certs | None = None
    """Sub-object providing certification point information."""
    character_id: int = Field(..., json_schema_extra={'x-cast-to': 'int64'})
    """Unique ID of the collection."""
    daily_ribbon: DailyRibbon | None = None
    """Sub-object for daily ribbon bonuses. Note that ribbon bonuses
    have been disabled, rendering this object useless. It is
    recommended to treat is as optional in client code in case it
    ever gets removed from the response object."""
    faction_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """Faction of the character. For NSOs, this equals the value of
    NSOs. An NSOs currently or home faction is not exposed on the
    REST API, but can be determined via the `team_id` of some
    WebSocket payloads."""
    head_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Identifier for the character's in-game model. Note that with
    gender change tokens, this is no longer guaranteed to be
    immutable across a character's career."""
    name: Name | None = None
    """Name of the character. Use the `first_lower` field for faster
    case-insensitive searches without needing to set `c:case=false`."""
    prestige_level: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The A.S.P. rank of the character."""
    profile_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class of the character when the last logged off. This value can
    generally only be one of the 24 infantry classes available in the
    legacy `ps2/profile` collection, though other values are possible
    due to bad data or deleted characters."""
    times: Times | None = None
    """Sub-object providing login time and playtime information."""
    title_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'title.title_id'},
    )
    """Currently selected title of the character. Useful for playing
    long names of players, e.g. "Snowblower Higby". A title ID of `0`
    corresponds to a player having selected "No Title" in-game."""
