# generated by datamodel-codegen:
#   filename:  characters_skill.yaml
#   timestamp: 2025-11-27T09:22:02+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CharactersSkill(RESTPayload):
    """List the skills unlocked by a character.
    This is used for both certifications and A.S.P. skills."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character side of the relationship."""
    last_save: str | None = None
    """UTC timestamp of when the underlying table was updated."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    skill_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'skill.skill_id'},
    )
    """Skill side of the relationship."""
