# generated by datamodel-codegen:
#   filename:  characters_friend.yaml
#   timestamp: 2025-11-27T09:21:52+00:00

from typing import List

from auraxium.models.base import RESTPayload
from pydantic import Field


class FriendListItem(RESTPayload):
    character_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character ID of the friend."""
    last_login_time: str | None = None
    """Last time the friend logged in."""
    online: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Whether the friend is currently online. Offline players will
    return 0, otherwise the value will be the `world_id` of the
    `ps2/world` they are online on."""


class CharactersFriend(RESTPayload):
    """Query the friends list of a character."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character for which the friends list is being returned."""
    friend_list: List[FriendListItem] | None = None
    name: str | None = None
    """Defunct."""
