# generated by datamodel-codegen:
#   filename:  currency.yaml
#   timestamp: 2025-11-27T09:22:19+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Currency(RESTPayload):
    """Lists currencies available in the game.

    As of 2023-06-13, the only currency available are Nanites. Outfit
    resources and other currencies such as Daybreak Cash, ISO-4, or
    A7 are not available on the API, while Cert Points and A.S.P.
    tokens are stored in the `character` collection."""

    currency_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the currency."""
    icon_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Icon ID of the resource. This is actually an `image_set_id`."""
    inventory_cap: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The maximum amount of this currency that can be held in a
    character's inventory."""
    name: LocalizedString | None = None
    """The name of the currency."""
