# generated by datamodel-codegen:
#   filename:  directive_tree.yaml
#   timestamp: 2025-11-27T09:22:27+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class DirectiveTree(RESTPayload):
    """A tree of directives sorted into multiple tiers.

    This collection represents the individual paths within a
    directive category, such as "Light Assault" or "Combat Medic"."""

    description: LocalizedString | None = None
    """The description of the directive tree."""
    directive_tree_category_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tree_category.directive_tree_category_id',
        },
    )
    """Unique ID of the category of the directive tree."""
    directive_tree_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the directive tree."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Unique ID of the default image."""
    image_path: str | None = Field(
        None, json_schema_extra={'x-reference-to': 'image.image_path'}
    )
    """Path to the default image."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Unique ID of the image set for this directive tree."""
    name: LocalizedString | None = None
    """The name of the directive tree."""
