# generated by datamodel-codegen:
#   filename:  directive_tree_category.yaml
#   timestamp: 2025-11-27T09:22:30+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class DirectiveTreeCategory(RESTPayload):
    """Top-level categorisation of directive trees.

    This covers the main sections in the Directive menu, such as
    "Infantry", "Vehicles", or "Events"."""

    directive_tree_category_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32'}
    )
    """Unique ID of the directive tree category."""
    name: LocalizedString | None = None
    """The name of the directive tree category."""
