# generated by datamodel-codegen:
#   filename:  directive.yaml
#   timestamp: 2025-11-27T09:22:21+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Directive(RESTPayload):
    """An individual directive that may be completed by a player.

    This collection lists an individual directive, such as "100
    Roadkills"."""

    description: LocalizedString | None = None
    """The description of the directive."""
    directive_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the directive."""
    directive_tier_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tier.directive_tier_id',
        },
    )
    """Unique ID of the directive tier."""
    directive_tree_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tree.directive_tree_id',
        },
    )
    """Unique ID of the directive tree."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Unique ID of the defaultimage."""
    image_path: str | None = Field(
        None, json_schema_extra={'x-reference-to': 'image.image_path'}
    )
    """Path to the default image."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Unique ID of the image set for this directive."""
    name: LocalizedString | None = None
    """The name of the directive."""
    objective_set_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'objective_set.objective_set_id',
        },
    )
    """Unique ID of the objective set."""
