# generated by datamodel-codegen:
#   filename:  directive_tier.yaml
#   timestamp: 2025-11-27T09:22:24+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class DirectiveTier(RESTPayload):
    """A completion tier within a directive tree.

    This covers the individual stages of directive tiers, such as
    "Combat Medic: Adept"."""

    completion_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The number of directives within this tier that must be completed
    to complete it."""
    directive_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The amount of directive points awarded for completing this
    directive tier."""
    directive_tier_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the directive tier."""
    directive_tree_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'directive_tree.directive_tree_id',
        },
    )
    """Unique ID of the directive tree this tier belongs to."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Unique ID of the default image."""
    image_path: str | None = Field(
        None, json_schema_extra={'x-reference-to': 'image.image_path'}
    )
    """Path to the default image."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Unique ID of the image set for this directive tier."""
    name: LocalizedString | None = None
    """The name of the directive tier."""
    reward_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'reward_set.reward_set_id',
        },
    )
    """Unique ID of the reward set awarded for completing this directive
    tier."""
