# generated by datamodel-codegen:
#   filename:  effect.yaml
#   timestamp: 2025-11-27T09:22:33+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Effect(RESTPayload):
    """A weapon-based effect acting on players or vehicles.

    Weapon-based effects include direct and indirect damage effects,
    tactical grenade impacts, as well as pseudo-weapons such as the
    Medic tool or Engineer repair tool. For world-based effects,
    weapon attachments and buffs, see the `zone_effect` collection
    instead.

    See the `effect_type` collection for a list of available effect
    types."""

    ability_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'ability.ability_id',
        },
    )
    """Unique identifier of the ability associated with this effect."""
    ability_type_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'ability_type.ability_type_id',
        },
    )
    """Unique identifier of the ability type associated with this
    effect."""
    duration_seconds: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Duration over which the effect is applied, in seconds."""
    effect_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    effect_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'effect_type.effect_type_id',
        },
    )
    """Unique identifier of the effect's type."""
    is_drain: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Unkown. Appears to control the resource drain of toggled
    abilities (e.g. Heavy Overshield) while they are active, among
    other things."""
    param1: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param10: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param11: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param12: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param13: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param2: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param3: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param4: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param5: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param6: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param7: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param8: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    param9: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/effect_type` for details."""
    resist_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'resist_type.resist_type_id',
        },
    )
    """Resist type used to calculate damage resistance for this effect."""
    target_type_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'target_type.target_type_id',
        },
    )
    """Target type used to select targets for this effect."""
