# generated by datamodel-codegen:
#   filename:  effect_type.yaml
#   timestamp: 2025-11-27T09:22:35+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class EffectType(RESTPayload):
    """A type of effect.

    The generic fields `paramX` and `stringX` are documented here.
    Note that not all fields are used by all effect types, or at all."""

    description: str
    """Description of the effect type."""
    effect_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    param1: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param10: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param11: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param12: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param13: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param2: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param3: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param4: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param5: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param6: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param7: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param8: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
    param9: str | None = None
    """Documentation for this numeric parameter on effects of this type."""
