# generated by datamodel-codegen:
#   filename:  empire_scores.yaml
#   timestamp: 2025-11-27T09:22:38+00:00

from auraxium.models.base import RESTPayload


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class EmpireScores(RESTPayload):
    """Defunct endpoint for the "World Domination Series" event scores."""

    end_date: str | None = None
    """Human-readable version of `end_time`."""
    end_time: str | None = None
    """UTC timestamp of when the event ended."""
    name: LocalizedString | None = None
    """Display name of the event."""
    start_date: str | None = None
    """Human-readable version of `start_time`."""
    start_time: str | None = None
    """UTC timestamp of when the event started."""
    tracker_description: str | None = None
    """Description of the tracker."""
    tracker_name: str | None = None
    """Unique name of the tracker."""
