# generated by datamodel-codegen:
#   filename:  event.yaml
#   timestamp: 2025-11-27T09:22:40+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field, RootModel


class EventBase(RESTPayload):
    event_type: str
    """Name of the event."""
    table_type: str
    """Internal name of the table."""
    timestamp: str
    """UTC timestamp of the event."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class WorldEvent1(EventBase):
    """ReST endpoint for retrieving historical world events.

    The `world_id` and `id` fields are interchangeable."""

    duration_held: str | None = None
    """Time in seconds since the facility was held by the previous
    owner."""
    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    facility_id: str | None = None
    """The ID of the facility that was captured."""
    faction_new: str | None = None
    """The faction that owns the facility after the capture."""
    faction_old: str | None = None
    """The faction that owned the facility before the capture."""
    objective_id: str | None = None
    """Unknown."""
    outfit_id: str | None = None
    """Unique ID of the outfit that captured the facility."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""


class WorldEvent2(EventBase):
    """ReST endpoint for retrieving historical world events.

    The `world_id` and `id` fields are interchangeable."""

    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    experience_bonus: str | None = None
    """Experience bonus for the winning faction."""
    faction_nc: str | None = None
    """Current scope of the NC faction."""
    faction_tr: str | None = None
    """Current scope of the TR faction."""
    faction_vs: str | None = None
    """Current scope of the VS faction."""
    instance_id: str | None = None
    """Unique ID of this particular instance of the metagame event. Only
    unique per server restart, not globally."""
    metagame_event_id: str | None = None
    """Unique ID of the metagame event."""
    metagame_event_state: str | None = None
    """Unique ID of the metagame event state."""
    metagame_event_state_name: str | None = None
    """Name of the metagame event state."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""


class WorldEvent(RootModel[WorldEvent1 | WorldEvent2]):
    root: WorldEvent1 | WorldEvent2
    """
    ReST endpoint for retrieving historical world events.

    The `world_id` and `id` fields are interchangeable.

    """


class CharactersEvent1(EventBase):
    """ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The
    `character_id` and `id` fields are interchangeable."""

    battle_rank: str | None = None
    """The new battle rank of the character."""
    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class CharactersEvent2(EventBase):
    """ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The
    `character_id` and `id` fields are interchangeable."""

    context: str | None = None
    """Identifier string for the conext in which the item was granted."""
    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    item_count: str | None = None
    """The number of items that were added."""
    item_id: str | None = None
    """The ID of the item that was added."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class CharactersEvent3(EventBase):
    """ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The
    `character_id` and `id` fields are interchangeable."""

    achievement_id: str | None = None
    """The ID of the achievement that was granted."""
    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class CharactersEvent4(EventBase):
    """ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The
    `character_id` and `id` fields are interchangeable."""

    attacker_character_id: str | None = None
    """The ID of the character that performed the kill."""
    attacker_fire_mode_id: str | None = None
    """The ID of the fire mode that was used to perform the kill."""
    attacker_vehicle_id: str | None = None
    """The ID of the vehicle that the attacker was in when they
    performed the kill."""
    attacker_weapon_id: str | None = None
    """The ID of the item that was used to perform the kill. Note that
    this is an item ID and not the weapon ID, despite the name."""
    character_loadout_id: str | None = None
    """The ID of the loadout that the dying player was playing as."""
    is_critical: str | None = None
    """Whether or not the kill was a critical hit. Not currently used by
    PlanetSide 2."""
    is_headshot: str | None = None
    """Whether or not the kill was a headshot."""
    event_type: str
    """Name of the event."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class CharactersEvent6(EventBase):
    """ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The
    `character_id` and `id` fields are interchangeable."""

    attacker_character_id: str | None = None
    """Unique ID of the player that destroyed the vehicle."""
    attacker_loadout_id: str | None = None
    """The ID of the loadout that the attacker was playing as."""
    attacker_player_guid: str | None = None
    """Unknown. Generally identical to `attacker_character_id`."""
    attacker_vehicle_id: str | None = None
    """The ID of the vehicle that the attacker was in when they
    destroyed the vehicle."""
    attacker_weapon_id: str | None = None
    """The ID of the item that was used to destroy the vehicle. Note
    that this is an item ID and not the weapon ID, despite the name."""
    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    faction_id: str | None = None
    """The ID of the faction that the vehicle belonged to."""
    projectile_id: str | None = None
    """Unknown. The IDs provided in this field are not available on the
    `projectile` endpoint."""
    vehicle_definition_id: str | None = None
    """The ID of the vehicle that was destroyed."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class CharactersEvent7(EventBase):
    """ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The
    `character_id` and `id` fields are interchangeable."""

    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    facility_id: str | None = None
    """The ID of the facility that was captured."""
    outfit_id: str | None = None
    """The ID of the outfit that captured the facility, or the facility
    that owns the facility at the time of defence."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class CharactersEvent(
    RootModel[
        CharactersEvent1
        | CharactersEvent2
        | CharactersEvent3
        | CharactersEvent4
        | CharactersEvent6
        | CharactersEvent7
    ]
):
    root: (
        CharactersEvent1
        | CharactersEvent2
        | CharactersEvent3
        | CharactersEvent4
        | CharactersEvent6
        | CharactersEvent7
    )
    """
    ReST endpoint for retrieving historical character event data.

    Like `event`, but allows querying by character. The `character_id` and `id` fields are interchangeable.

    """


class Event(RootModel[CharactersEvent | WorldEvent]):
    root: CharactersEvent | WorldEvent
    """
    ReST endpoint for retrieving historical event data.

    These largely mirror the corresponding events in the ESS:

    - `ItemAdded` -> `ITEM`
    - `Death` -> `KILL`/`DEATH`
    - `BattleRankUp` -> `BATTLE_RANK`
    - `PlayerFacilityCapture`/`PlayerFacilityDefend` -> `FACILITY_CHARACTER`
    - `AchievementEarned` -> `ACHIEVEMENT`
    - `FacilityControl` -> `FACILITYCONTROL`
    - `MetagameEvent` -> `METAGAME`"

    """
