# generated by datamodel-codegen:
#   filename:  experience_rank.yaml
#   timestamp: 2025-11-27T09:22:48+00:00

from typing import Any

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class ExperienceRankFaction(RESTPayload):
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """The `ps2/image` of the rank for the given faction."""
    image_path: str | None = Field(
        None, json_schema_extra={'x-reference-to': 'image.path'}
    )
    """The path to the image of the rank for the given faction."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """The `ps2/image_set` of the rank for the given faction."""
    title: LocalizedString | None = None
    """The title of the rank for the given faction."""


class ExperienceRank(RESTPayload):
    """Player rank gained through leveling up.

    Note that the `rank` field is not unique, as each rank is
    duplicated for each prestige (aka. A.S.P.) level. The prestige
    entries can only be distinguished by their icons."""

    nc: ExperienceRankFaction
    """Subkey for the New Conglomerate."""
    nc_image_path: Any | None = None
    """Path to the facion-specific icon for this experience rank."""
    rank: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """The ordinal rank of the experience type. Note that this is the
    same for each prestige level (0 through 3)."""
    tr: ExperienceRankFaction
    """Subkey for the Terran Republic."""
    tr_image_path: Any | None = None
    """Path to the facion-specific icon for this experience rank."""
    vs: ExperienceRankFaction
    """Subkey for the Vanu Sovereignty."""
    vs_image_path: Any | None = None
    """Path to the facion-specific icon for this experience rank."""
    xp_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unused."""
