# generated by datamodel-codegen:
#   filename:  experience.yaml
#   timestamp: 2025-11-27T09:22:43+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Experience(RESTPayload):
    """Lists the different types of experience ticks."""

    description: str | None = None
    """Description of the experience type."""
    experience_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    xp: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The amount of XP granted by this experience type."""
    experience_award_type_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Unique ID of th experience award type of this experience tick."""
