# generated by datamodel-codegen:
#   filename:  experience_award_type.yaml
#   timestamp: 2025-11-27T09:22:45+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ExperienceAwardType(RESTPayload):
    """Experience type, such as "Kill Assist".

    Groups experience ticks. For example, "Kill Assist - Flash" and
    "Kill Player Assist" are both part of the "KillAssist" award
    type."""

    description: str | None = None
    """Internal name/description of the experience type (e.g. "Revive",
    "KillAssist")"""
    experience_award_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection"""
