# generated by datamodel-codegen:
#   filename:  facility_link.yaml
#   timestamp: 2025-11-27T09:22:51+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class FacilityLink(RESTPayload):
    """Resolves lattice links between facilities.

    There is no reliable difference between `facility_id_a` and
    `facility_id_b`; the former tends to be closer to the respective
    warpgate, but this does not hold true for all links. It is
    recommended to treat the link direction as arbitrary."""

    description: str | None = None
    """The description of the facility link."""
    facility_id_a: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'map_region.facility_id',
        },
    )
    """The ID of the first facility in the link."""
    facility_id_b: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'map_region.facility_id',
        },
    )
    """The ID of the second facility in the link."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone in which the facility link is located."""
