# generated by datamodel-codegen:
#   filename:  facility_type.yaml
#   timestamp: 2025-11-27T09:22:53+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class FacilityType(RESTPayload):
    """Lists all facility types across all zones and game modes."""

    description: str
    """Description of the facility type."""
    facility_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Default image of the facility type's map icon."""
    image_path: str | None = None
    """The path to the facility type's map icon."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """The `ps2/image_set` of the facility type's map icon."""
