# generated by datamodel-codegen:
#   filename:  faction.yaml
#   timestamp: 2025-11-27T09:22:56+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Faction(RESTPayload):
    """Endpoint for playable and non-playable factions.
    In addition to the main empires VS, NC, and TR, this also lists
    NS Operatives as the 4th faction. Note that a faction ID of zero
    does not denote an empty value. Instead, it represents a special
    "None" faction, which is used for common pool equipment, and also
    serves as a sentinel value for disabled facilities in the context
    of facility ownership.
    When working with the Event Streaming Service (ESS), you will
    encounter a `team_id` field in certain payloads. This is used to
    control friend-or-foe status for NSO players, or for the opposing
    factions in Outfit Wars.
    During regular gameplay (i.e. outside of Outfit Wars), it is
    generally safe to treat a team ID as a faction. However, care
    should be taken during Outfit Wars matches as the team IDs will
    map to the Alpha and Omega team instead."""

    code_tag: str
    """The unique tag of the faction, or `None` for common-pool nanite
    systems."""
    faction_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """The `ps2/image` of the faction."""
    image_path: str | None = None
    """Relative path to the default image of the faction."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """The `ps2/image_set` of the faction."""
    name: LocalizedString | None = None
    """Canonical name of the faction"""
    user_selectable: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether this faction is playable or reserved for NPCs."""
