# generated by datamodel-codegen:
#   filename:  fire_mode_2.yaml
#   timestamp: 2025-11-27T09:23:06+00:00

from typing import Any

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class FireMode2(RESTPayload):
    """Main endpoint for baseline weapon characteristics and firing
    mechanics. This includes:

    - Damage effects and ranges
    - Recoil magnitude and pattern
    - Triggered abilities for pseudo-weapons such as the medical
      applicator
    - Ammunition consumption and pellet count
    - Heat-mechanics

    Be aware that lockon information is currently disconnected from
    the game data and has not
    been outdated. Refer to the PS2 Wiki for up-to-date information
    for the time being."""

    ability_block_delay_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Delay in milliseconds before the player can use an ability after
    firing."""
    ability_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'ability.ability_id',
        },
    )
    """The ability trigger upon firing pseudo-weapons such as the
    Medical Applicator or Repair Tool."""
    ammo_slot: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The ammo slot connected to this fire mode in the corresponding
    weapon. Can be matched to the `ps2/weapon.weapon_slot_index`
    field."""
    armor_penetration: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Unused."""
    automatic: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether the fire mode is automatic or not, i.e. whether it will
    refire on its own if the trigger is held down. Note that this may
    conflict with the fire mode's `description`, in particular for
    vehicle weapons."""
    bullet_arc_kick_angle: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Initial upwards angle in degrees applied to the bullet
    trajectory. Used to compensate for bullet drop."""
    charge_minimum_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Minimum charge time before the weapon can be fired."""
    cof_override: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Unused."""
    cof_pellet_spread: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Spread between pellets in degrees."""
    cof_range: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    cof_recoil: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Cone of fire bloom per shot in degrees."""
    cof_scalar: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Multiplier for the cone of fire values from the corresponding
    `ps2/player_state_group_2`."""
    cof_scalar_moving: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Multiplier for the cone of fire values from the corresponding
    `ps2/player_state_group_2` while moving."""
    damage_direct_effect_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'effect.effect_id'},
    )
    """The `ps2/effect` applied to the target upon a direct hit."""
    damage_head_multiplier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Relative headshot damage offset. Add 1 and multiple with the base
    damage to get the actual damage dealt."""
    damage_indirect_effect_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'effect.effect_id'},
    )
    """The splash damage `ps2/effect` applied to targets near the
    impact."""
    damage_legs_multiplier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Relative legshot damage offset. Add 1 and multiple with the base
    damage to get the actual damage dealt."""
    description: LocalizedString | None = None
    """Player-facing description of the fire mode, such as "Semi-
    Automatic", "Automatic", or "Underbarrel"."""
    fire_ammo_per_shot: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Ammo consumed per shot."""
    fire_auto_fire_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Delay between shots in a burst in milliseconds."""
    fire_burst_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of shots in a burst."""
    fire_charge_up_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Charge-up time in milliseconds."""
    fire_delay_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Delay between pulling the trigger and the first shot in
    milliseconds."""
    fire_detect_range: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Default minimap auto-detect range of the fire mode."""
    fire_duration_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Duration of the fire animation in milliseconds. Used for pseudo-
    weapons such as recon darts, spawn beacons, or deployables."""
    fire_mode_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'fire_mode.fire_mode_id',
        },
    )
    """Unique ID of the fire mode."""
    fire_mode_type_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'fire_mode_type.fire_mode_type_id',
        },
    )
    """The `ps2/fire_mode_type` of the fire mode."""
    fire_pellets_per_shot: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Number of pellets fired per shot. Used for shotguns, as well as
    some outliers like the NSX Tengu or VEC Horizon."""
    fire_refire_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Delay before the weapon can be fired again after releasing the
    trigger."""
    grief_immune: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """If true, the fire mode is not considered as part of the grief
    points system and can not cause a weapon lock."""
    heat_per_shot: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Heat generated per shot. Together with `heat_threshold`, this
    provides an estimation of the effective magazine size of heat-
    based weapons."""
    heat_recovery_delay_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Delay before heat starts to recover after firing stops."""
    heat_threshold: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Heat threshold before the weapon overheats. Together with
    `heat_per_shot`, this provides an estimation of the effective
    magazine size of heat-based weapons."""
    iron_sights: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    laser_guided: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """If true, projectiles fired will continue to follow the crosshair
    after firing."""
    lockon_acquire_close_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Time required to establish a lock at a distance of
    `lockon_range_close` metres. Interpolated linearly."""
    lockon_acquire_far_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Time required to establish a lock at a distance of
    `lockon_range_far` metres. Interpolated linearly."""
    lockon_acquire_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Defunct field. Always returns zero."""
    lockon_angle: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Field of view of the cone within which targets may be locked."""
    lockon_lose_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Period in which an already established lock remains active after
    losing line of sight with the target. This is the window during
    which the player may flick the mouse to shoot around obstacles."""
    lockon_maintain: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    lockon_radius: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Defunct field. Always returns zero."""
    lockon_range: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Defunct field. Always returns zero."""
    lockon_range_close: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Distance at which `lockon_acquire_close_ms` is applied. Note that
    this is not a minimum distance from the target, only a lower
    bound for the lock-on time."""
    lockon_range_far: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Distance at which `lockon_acquire_far_ms` is applied. Note that
    this may not line up with the maximum range at which a lock can
    be established."""
    lockon_required: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    max_damage: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Maximum direct damage amount. For weapons with damage fall-off,
    this is applied at `max_damage_range`."""
    max_damage_ind: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Maximum indirect damage amount at the centre of the blast radius."""
    max_damage_ind_radius: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Inner radius of the indirect damage effect at which
    `max_damage_ind` is applied."""
    max_damage_range: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Distance at which `max_damage` is applied."""
    min_damage: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Minimum direct damage amount. For weapons with damage fall-off,
    this is applied at `min_damage_range`. For weapons with a flat
    damage profile, only `max_damage` may be set, with this field
    being NULL."""
    min_damage_ind: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Indirect damage amount at the edge of the blast radius."""
    min_damage_ind_radius: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Outer edge of the indirect damage blast radius where
    `min_damage_ind` is applied."""
    min_damage_range: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Distance at which `min_damage` is applied."""
    move_modifier: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Movement speed modifier applied while the fire mode is active."""
    player_state_group_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'player_state_group.player_state_group_id',
        },
    )
    """The `ps2/player_state_group` controlling this fire mode."""
    projectile_speed_override: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Optional override for the base movement speed defined in the
    corresponding projectile."""
    recoil_angle_max: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Maximum recoil angle in degrees. Recoil angles is measured
    clockwise relative to vertical, so a positive value means the
    weapon will pull to the right. This defines the basic axis of the
    recoil pattern, "horizontal" recoil is orthogonal to this axis."""
    recoil_angle_min: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Minimum recoil angle in degrees. Recoil angles is measured
    clockwise relative to vertical, so a positive value means the
    weapon will pull to the right. This defines the basic axis of the
    recoil pattern, "horizontal" recoil is orthogonal to this axis."""
    recoil_first_shot_modifier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Vertical recoil multiplier for the first shot in a burst."""
    recoil_horizontal_max: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Upper limit for the horizontal recoil per shot in degrees."""
    recoil_horizontal_max_increase: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Like `reload_increase`, but only affects the horizontal recoil
    components."""
    recoil_horizontal_min: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Upper limit for the horizontal recoil per shot in degrees."""
    recoil_horizontal_min_increase: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Like `reload_increase`, but only affects the horizontal recoil
    components."""
    recoil_horizontal_tolerance: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Symmetric tolerance for the horizontal recoil pattern. After
    exceeding half of this value in either direction, the recoil is
    guaranteed to kick back towards the center for the next shot."""
    recoil_increase: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Recoil increase per shot in degrees."""
    recoil_increase_crouched: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Recoil increase per shot in degrees while crouched."""
    recoil_magnitude_max: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Maximum recoil magnitude in degrees."""
    recoil_magnitude_min: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Minimum recoil magnitude in degrees."""
    recoil_max_total_magnitude: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Total recoil limit in degrees."""
    recoil_recovery_acceleration: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Acceleration of the recoil recovery. High values lead to linear
    recoil recovery."""
    recoil_recovery_delay_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Delay before the recoil recovery starts in milliseconds."""
    recoil_recovery_rate: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Recoil recovery rate in degrees per second."""
    recoil_shots_at_min_magnitude: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Number of shots fired before the recoil magnitude starts to
    decrease."""
    reload_ammo_fill_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """For magazine-fed weapons, the actual time of the reload, not
    counting the animation or chambering time."""
    reload_block_auto: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """If true, an empty magazine will force the player out of ADS in
    order to reload."""
    reload_chamber_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """For weapons with magazines, the extra time taken to chamber after
    a reload. To calculate the long reload, add this value to
    `reload_time_ms`."""
    reload_continuous: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether the weapon uses a per-shell reload animation, such as
    pump-action shotguns."""
    reload_loop_end_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """For tube-fed weapons (pump-action shotguns), the final delay
    after reloading is complete or has been cancelled before the
    weapon can fire."""
    reload_loop_start_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """For tube-fed weapons (pump-action shotguns), the initial delay
    before the first shell is chambered."""
    reload_time_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Reload time in milliseconds. For magazine-fed weapons, this is
    the short reload. For tube-fed weapons (pump-action shotguns),
    this represents the reload interval."""
    shield_bypass_pct: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    sprint_block_delay_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Delay in milliseconds before the player can start sprinting after
    firing."""
    sprint_fire: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether the firte mode can be used while sprinting."""
    sway_amplitude_x: int | None = Field(None, json_schema_extra={'x-cast-to': 'int'})
    """Amplitude of the sinusoidal scope sway in degrees."""
    sway_amplitude_y: int | None = Field(None, json_schema_extra={'x-cast-to': 'int'})
    """Amplitude of the sinusoidal scope sway in degrees."""
    sway_can_steady: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether scope sway can be steadied by holding breath."""
    sway_period_x: int | None = Field(None, json_schema_extra={'x-cast-to': 'int'})
    """Period of the sinusoidal scope sway in seconds."""
    sway_period_y: int | None = Field(None, json_schema_extra={'x-cast-to': 'int'})
    """Period of the sinusoidal scope sway in seconds."""
    turn_modifier: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Turn speed modifier applied while the fire mode is active."""
    use_in_water: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether the fire mode can be used while submerged."""
    zoom_default: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Default zoom level for the fire mode."""
