# generated by datamodel-codegen:
#   filename:  fire_mode.yaml
#   timestamp: 2025-11-27T09:23:03+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class FireMode(RESTPayload):
    """**Note:** This table has been largely superceded by
    `fire_mode_2`, which contains additional and more accurate
    information about firing mechanics.

    This endpoint shows detailed information about a given fire mode
    for a weapon, including damage ranges, muzzle velocity, and
    reload time.

    For details on the cone-of-fire mechanics, resolve the
    `player_state_group_id` field."""

    cof_recoil: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Baseline cone-of-fire bloom per shot. See the corresponding
    `ps2/player_state_group` for more information."""
    damage: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Flat damage amount for weapons without damage fall-off, such as
    knives."""
    damage_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Maximum direct damage for weapons with damage fall-off."""
    damage_max_range: int | None = Field(None, json_schema_extra={'x-cast-to': 'int'})
    """Range up to which the maximum direct projectile damage is
    applied."""
    damage_min: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Minimum direct damage for weapons with damage fall-off."""
    damage_min_range: int | None = Field(None, json_schema_extra={'x-cast-to': 'int'})
    """Range at which the minimum direct projectile damage is reached
    and no further damage fall-off is applied."""
    damage_radius: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    damage_resist_type: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'resist_type.resist_type_id',
        },
    )
    """Damage resist type used for direct hits. See `ps2/resist_type`
    for more information."""
    damage_target_type: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'target_type.target_type_id',
        },
    )
    """Target types that can be damaged by this weapon's direct hits.
    See `ps2/target_type` for more information."""
    damage_type: str | None = None
    """Description of the type of damage effect."""
    default_zoom: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Default zoom level for this fire mode."""
    description: LocalizedString | None = None
    """Range description for this fire mode."""
    fire_mode_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'fire_mode.fire_mode_id',
        },
    )
    """Unique ID of the collection."""
    indirect_damage_max: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Maximum indirect damage for weapons with damage fall-off."""
    indirect_damage_max_range: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Range at which the maximum indirect projectile damage is applied."""
    indirect_damage_min: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Minimum indirect damage for weapons with damage fall-off."""
    indirect_damage_min_range: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """^Range at which the minimum indirect projectile damage is reached
    and no further damage fall-off is applied."""
    indirect_damage_resist_type: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Damage resist type used for indirect hits. See `ps2/resist_type`
    for more information."""
    indirect_damage_target_type: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Target types that can be damaged by this weapon's indirect hits.
    See `ps2/target_type` for more information."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The `ps2/item` to which this fire mode belongs. Note that this
    field is unreliable and may point to arbitrary item IDs in
    addition to the corresponding weapon item."""
    max_speed: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """On self-propelled projectiles, the upper speed cap of the
    projectile. Used to increase projectile speed over time for lock-
    on launchers."""
    muzzle_velocity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Muzzle velocity of ballistic projectile in meters per second."""
    pellet_spread: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Spread between pellets in degrees."""
    pellets_per_shot: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of pellets fired per shot. Used for shotguns, as well as
    some outliers like the NSX Tengu or VEC Horizon."""
    player_state_group_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'player_state_group.player_state_group_id',
        },
    )
    """Player state group associated with this fire mode. Contains
    state-dependent characteristics such as cone-of-fire."""
    projectile_description: str | None = None
    """Internal description of the projectile used."""
    reload_chamber_time_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Rechamber time after a reload. To calculate the long reload of a
    weapon, add this value to `reload_time_ms`."""
    reload_time_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Short reload duration in milliseconds."""
    speed: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """On self-propelled projectiles, the initial speed of the
    projectile in meters per second."""
    type: str | None = None
    """Type description for the fire mode. Useful when needing to
    distinguish between multiple fire modes on a given weapon."""
