# generated by datamodel-codegen:
#   filename:  fire_group_to_fire_mode.yaml
#   timestamp: 2025-11-27T09:23:01+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class FireGroupToFireMode(RESTPayload):
    fire_group_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'fire_group.fire_group_id',
        },
    )
    """Fire group side of the relationship."""
    fire_mode_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'fire_mode_2.fire_mode_id',
        },
    )
    """Fire mode side of the relationship."""
    fire_mode_index: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Index of the fire mode within the fire group."""
