# generated by datamodel-codegen:
#   filename:  fire_mode_type.yaml
#   timestamp: 2025-11-27T09:23:11+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class FireModeType(RESTPayload):
    """Enumeration of the types of fire modes.

    This servers to differentiate between melee attacks, projectile
    weapons, throwables, and pseudo-weapon fire modes used to trigger
    activated items."""

    description: str
    """Description of the type of fire mode"""
    fire_mode_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the fire mode type."""
