# generated by datamodel-codegen:
#   filename:  fire_group.yaml
#   timestamp: 2025-11-27T09:22:58+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class FireGroup(RESTPayload):
    """Fire groups in the API are synonymous with fire modes in-game,
    they represent the different operating modes some weapons can
    switch between.

    This includes select-fire modes for infantry weapons, as well as
    knives switching between quick knife, wielded knive, and - in the
    case of power knives - the one-hit-kill mode."""

    can_chamber_ironsights: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether the weapon can be chambered while aiming down sights.
    Only set on weapons with this capability by default, weapons
    requiring attachments such as straight-pull bolts will not have
    this set."""
    chamber_duration_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """The time between shots on bolt action or pump action weapons."""
    fire_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    spool_up_initial_refire_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Initial refire time (inverse of fire rate) for spool-up weapons."""
    spool_up_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Time to reach maximum fire rate on spool-upup weapons."""
    transition_duration_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Time to transition to this fire group on select-fire weapon."""
