# generated by datamodel-codegen:
#   filename:  fire_mode_to_projectile.yaml
#   timestamp: 2025-11-27T09:23:08+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class FireModeToProjectile(RESTPayload):
    """Maps fire modes to their projectiles."""

    fire_mode_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'fire_mode.fire_mode_id',
        },
    )
    """Fire mode side of the relationship."""
    projectile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'projectile.projectile_id',
        },
    )
    """Projectile side of the relationship."""
