# generated by datamodel-codegen:
#   filename:  fish.yaml
#   timestamp: 2025-11-27T09:23:14+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Fish(RESTPayload):
    fish_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    name: LocalizedString | None = None
    """Display name of the fish."""
    rarity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Rarity level of the fish (1 through 3)."""
    size: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Size category of the fish (1 through 4)."""
    average_size: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Average size of the fish."""
    size_deviation: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Standard deviation of the fish size in centimeters."""
    scan_point_amount: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Number of points awarded for scanning this fish."""
    cost: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Price of the fish."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """The `ps2/image` of the item's display icon."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """The `ps2/image_set` of the item's display icon."""
