# generated by datamodel-codegen:
#   filename:  image_set_default.yaml
#   timestamp: 2025-11-27T09:23:22+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ImageSetDefault(RESTPayload):
    """Lists the default image for a given image set."""

    description: str | None = None
    """Description of the image set."""
    image_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """ID of the image asset for this image set and type."""
    image_path: str | None = None
    """Relative to the image asset. Prefix the base URL to the Census
    API endpoint to create a fully-qualified URL."""
    image_set_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """ID of the image set. Note that this is not a unique ID, this
    collection is a mapping."""
    type_description: str | None = None
    """Type description of the current image within the set. Usually,
    this refers to scale."""
    type_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Type ID of the current image within the set. Usually, this refers
    to scale."""
