# generated by datamodel-codegen:
#   filename:  image.yaml
#   timestamp: 2025-11-27T09:23:17+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Image(RESTPayload):
    """Lists individual image assets available on the API.

    Note that historically, not all assets listed here are available
    on the image endpoint, and not all available assets are listed."""

    description: str | None = None
    """Description of the asset."""
    image_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the image."""
    path: str | None = None
    """Relative to the image asset. Prefix the base URL to the Census
    API endpoint to create a fully-qualified URL."""
