# generated by datamodel-codegen:
#   filename:  image_set.yaml
#   timestamp: 2025-11-27T09:23:19+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ImageSet(RESTPayload):
    """Lists related image assets belonging to the same set.

    Note that this endpoint is a mapping; the `image_set_id` is not a
    unique key. The individual image types in a set are generally
    used to provide different sizes of the same image (e.g. icon
    previes or minimal icons)."""

    description: str | None = None
    """Description of the image set."""
    image_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """ID of the image asset for this image set and type."""
    image_path: str | None = None
    """Relative to the image asset. Prefix the base URL to the Census
    API endpoint to create a fully-qualified URL."""
    image_set_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """ID of the image set. Note that this is not a unique ID, this
    collection is a mapping."""
    type_description: str | None = None
    """Type description of the current image within the set. Usually,
    this refers to scale."""
    type_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Type ID of the current image within the set. Usually, this refers
    to scale."""
