# generated by datamodel-codegen:
#   filename:  item_type.yaml
#   timestamp: 2025-11-27T09:23:37+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ItemType(RESTPayload):
    """Items in PlanetSide 2 represent many different things beyond
    weapons, such as implant packs, cosmetics, or name change tokens.
    They are also used as internal helpers when pulling outfit
    resources, spawning vehicles, or interacting with certain
    terminals.

    This collection lists the different item types, though many of
    these are never encountered on the API."""

    code: str | None = None
    """Internal code of the item type."""
    item_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'item_type.item_type_id',
        },
    )
    """Unique ID of the collection."""
    name: str | None = None
    """Display name of the item type."""
