# generated by datamodel-codegen:
#   filename:  item_profile.yaml
#   timestamp: 2025-11-27T09:23:32+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ItemProfile(RESTPayload):
    """Maps items to profiles (classes/vehicles) that have access to
    them."""

    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""
    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Profile side of the relationship."""
