# generated by datamodel-codegen:
#   filename:  item_category.yaml
#   timestamp: 2025-11-27T09:23:29+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class ItemCategory(RESTPayload):
    """Item categories are used to group items together for display in
    the loadout screen or depot."""

    item_category_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'item_category.item_category_id',
        },
    )
    """Unique ID of the collection."""
    name: LocalizedString | None = None
    """Display name of the item category."""
