# generated by datamodel-codegen:
#   filename:  item.yaml
#   timestamp: 2025-11-27T09:23:24+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Item(RESTPayload):
    """Items in PlanetSide 2 are used to represent weapons, tools, and
    consumables, but also cosmetic items and internal control objects
    for player renaming or outfit resource consumption. Use the
    `item_type` collection to narrow searches to specific types."""

    activatable_ability_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'ability.ability_id',
        },
    )
    """The active `ps2/ability` granted upon equipping this item, such
    as the Heavy Assault's Overshield or MAX abilities."""
    description: LocalizedString | None = None
    """Description of the item."""
    faction_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """The `ps2/faction` of the item. Items with a faction ID of 0 are
    common-pool and available to all factions."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """The `ps2/image` of the item's display icon."""
    image_path: str | None = None
    """Relative path to the default image of the item."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """The `ps2/image_set` of the item's display icon."""
    is_default_attachment: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """If true, the item is auto-granted to the player, such as the
    default scope and ammo types."""
    is_vehicle_weapon: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether this item is a vehicle weapon."""
    item_category_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'item_category.item_category_id',
        },
    )
    """The `ps2/item_category` of the item."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Unique ID of the collection."""
    item_type_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'item_type.item_type_id',
        },
    )
    """The `ps2/item_type` of the item."""
    max_stack_size: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The maximum number of this item that can be held at once.
    Primarily used for consumables or carried explosives."""
    name: LocalizedString | None = None
    """Display name of the item."""
    passive_ability_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'ability.ability_id',
        },
    )
    """The passive `ps2/ability` granted upon equipping this item, such
    as a suppressor or scope."""
    skill_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'skill_set.skill_set_id',
        },
    )
    """The `ps2/skill_set` of the item. Remnant of the original
    certification menu, used to unlock the weapon in the
    certification skill tree and lock out purchasing of attachments
    for weapons the player has not unlocked yet."""
