# generated by datamodel-codegen:
#   filename:  item_to_weapon.yaml
#   timestamp: 2025-11-27T09:23:34+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ItemToWeapon(RESTPayload):
    """Maps items (including name, availability) to its respective
    weapon object.

    Not all items have a weapon objects, though some filtering can be
    done through the `item_type_id` field, with the ID 26
    representing most weapon types."""

    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""
    weapon_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'weapon.weapon_id'},
    )
    """Weapon side of the relationship."""
