# generated by datamodel-codegen:
#   filename:  item_attachment.yaml
#   timestamp: 2025-11-27T09:23:27+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ItemAttachment(RESTPayload):
    """Maps attachment items to the items they can be attached to."""

    attachment_item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item that can be attached to the `item_id`."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Host item the `attachment_item_id` can be attached to."""
