# generated by datamodel-codegen:
#   filename:  leaderboard.yaml
#   timestamp: 2025-11-27T09:23:40+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Leaderboard(RESTPayload):
    """Global leaderboard for a given server. This only includes the top
    10'000 players for a given category and is not directly
    searchable. See `characters_leaderboard` to look up a character's
    ranking.

    `c:start` and `c:limit` are supported and allow for pagination.
    `c:join` and `c:tree` are also permitted. Any other query
    commands will be silently ignored.

    Unlike most other tables, this one defaults to a `c:limit` value
    of 10 and is always sorted in ascending order of leaderboard
    rank."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The ID of the character."""
    rank: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """The rank of the character for the given statistic."""
    value: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given statistic."""
