# generated by datamodel-codegen:
#   filename:  loadout.yaml
#   timestamp: 2025-11-27T09:23:42+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Loadout(RESTPayload):
    """Enumeration of the six infantry classes for each playable
    faction.

    Note that this is different from the in-game loadouts, which are
    not available on the API."""

    code_name: str | None = None
    """Internal name of the loadout."""
    faction_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """The `ps2/faction` of the loadout."""
    loadout_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """The `ps2/profile_2` matching this loadout."""
