# generated by datamodel-codegen:
#   filename:  map.yaml
#   timestamp: 2025-11-27T09:23:45+00:00

from typing import List

from auraxium.models.base import RESTPayload
from pydantic import Field


class RowData(RESTPayload):
    FactionId: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """Faction that owns the region."""
    RegionId: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'map_region.map_region_id',
        },
    )
    """Region for which ownership data is returned."""


class RowItem(RESTPayload):
    RowData_1: RowData | None = Field(None, alias='RowData')


class Regions(RESTPayload):
    IsList: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Irrelevant field, always true."""
    Row: List[RowItem] | None = None
    """List of map row entries."""


class Map(RESTPayload):
    """Map status endpoint.

    This collection can only be queried with a single `world_id` and
    any number of `zone_ids` (note that the parameter is plural).
    Also note the non-standard payload format requiring different
    parsing rules.

    For partially locked continents, the unavailable regions will
    report a `FactionId` of zero."""

    Regions_1: Regions | None = Field(None, alias='Regions')
    ZoneId: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """Zone for which map data is returned."""
