# generated by datamodel-codegen:
#   filename:  map_hex.yaml
#   timestamp: 2025-11-27T09:23:48+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class MapHex(RESTPayload):
    """Endpoint for retrieving map hex coordinates.
    This data can be used to reconstruct the in-game facility
    outlines from API data.

    The X and Y coordinates listed in the entries to this collection
    are not Cartesian and do not match up with the `location_<n>`
    fields of `map_region`. Instead, they are describing locations in
    a non-orthogonal hexagonal grid, which must be converted by the
    user.

    This website has a great write-up on hexagonal coordinate
    systems: <https://www.redblobgames.com/grids/hexagons/>.
    The coordinate system used by PlanetSide 2 matches the "Axial
    coordinates" described in the article, except that the first
    coordinate X faces east, and the second coordinate Y faces up and
    to the right at a 60° angle."""

    hex_type: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Type of the hex. 0: capturable by anyone, 1: not capturable, 2:
    locked to a single faction."""
    map_region_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'map_region.map_region_id',
        },
    )
    """Region for which a hex is returned."""
    type_name: str | None = None
    """Name of the hex type."""
    x: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """X coordinate of the hex. See the endpoint documentation for
    `map_hex` for details on converting these indices into Cartesian
    coordinates."""
    y: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Y coordinate of the hex. See the endpoint documentation for
    `map_hex` for details on converting these indices into Cartesian
    coordinates."""
    zone_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """Zone containing the region for which a hex is returned."""
