# generated by datamodel-codegen:
#   filename:  map_region.yaml
#   timestamp: 2025-11-27T09:23:51+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class CaptureReward(RESTPayload):
    amount: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Amount of the outfit resource granted for capturing this region."""
    description: str | None = None
    """Internal name of the outfit resource granted for capturing this
    region."""


class TickReward(RESTPayload):
    amount: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Amount of the outfit resource granted per tick while holding this
    region."""
    description: str | None = None
    """Internal name of the outfit resource granted while holding this
    region."""


class MapRegion(RESTPayload):
    """A region on the in-game map.

    Map regions are largely identical to their corresponding regions,
    but use the internal `facility_name` instead of a localized
    string. A `map_region_id` and `region_id` are interchangeable.

    Additionally, this collection allows connecting facilities to map
    region IDs.

    Note that the continuous outfit resource gain is listed in
    "ticks", not minutes. Ticks are 5 minutes as of writing, meaning
    that a Tech Plant will list a tick reward of 8 Synthium,
    corresponding to the 1.6 Synthium per minute advertised in-game."""

    capture_reward: CaptureReward | None = None
    facility_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Capturable facility associated with the map region. Note that
    some regions do not have facilities associated with them, such as
    The Shattered Warpgate."""
    facility_name: str | None = None
    """Internal name of the facility. See the corresponding `region` for
    a localized value."""
    facility_type: str | None = None
    """Internal name of the facility type."""
    facility_type_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'facility_type.facility_type_id',
        },
    )
    """Type of the facility associated with the map region."""
    location_x: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """North-south coordinate of the map region."""
    location_y: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Elevation of the map region."""
    location_z: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """East-west coordinate of the map region."""
    map_region_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    reward_amount: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Defunct field. Used to list the amount of domain-specific
    resources (air/vehicles/infantry) granted for owning this
    facility."""
    reward_currency_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Defunct field. Used to list the type of domain-specific resources
    (air/vehicles/infantry) granted for owning this facility."""
    tick_reward: TickReward | None = None
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """Zone the map region is located in."""
