# generated by datamodel-codegen:
#   filename:  marketing_bundle.yaml
#   timestamp: 2025-11-27T09:23:54+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class MarketingBundle(RESTPayload):
    """Bundles available for purchase in the in-game store (Depot). This
    collection represents actual bundles. For pseudo-bundles used to
    purchase individual weapon attachments or cosmetics, see the
    `marketing_bundle_with_1_item` collection instead.

    Note that there is no guaranteed way of determining whether a
    given bundle is currently available for purchase. This collection
    contains many entries for defunct items and bundles, such as the
    single-use camos from the early days of the game.

    This collection is automatically maintained and generally
    accurate with regards to certification prices, the
    daybreak/station cash values are generally less reliable."""

    cert_price: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The price of the marketing bundle in Certification Points."""
    description: LocalizedString | None = None
    """Description of the marketing bundle."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """The `ps2/image` of the marketing bundle's display icon."""
    marketing_bundle_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'marketing_bundle.marketing_bundle_id',
        },
    )
    """Unique ID of the collection."""
    name: LocalizedString | None = None
    """Display name of the marketing bundle."""
    release_time: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The time the marketing bundle was released as a UTC timestamp."""
    station_cash_price: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """The price of the marketing bundle in Station Cash."""
