# generated by datamodel-codegen:
#   filename:  marketing_bundle_with_1_item.yaml
#   timestamp: 2025-11-27T09:24:00+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class MarketingBundleWith1Item(RESTPayload):
    """These are pseudo-bundles with exactly 1 item each, allowing
    players to buy individual weapons or cosmetics with Daybreak Cash
    (formerly Station Cash).

    Note that in the case of weapons, these bundles are genreally
    mirrored by 'regular' bundles in the `marketing_bundle`
    collection, with the same `marketing_bundle_id`."""

    cert_price: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The price of the marketing bundle in Certification Points."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""
    item_quantity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The quantity of the item in the marketing bundle."""
    marketing_bundle_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'marketing_bundle_with_1_item.marketing_bundle_id',
        },
    )
    """Marketing bundle side of the relationship."""
    release_time: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The time the marketing bundle was released as a UTC timestamp."""
    station_cash_price: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """The price of the marketing bundle in Daybreak Cash (formerly
    Station Cash)."""
