# generated by datamodel-codegen:
#   filename:  marketing_bundle_item.yaml
#   timestamp: 2025-11-27T09:23:58+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class MarketingBundleItem(RESTPayload):
    """Maps marketing bundles to the items they contain."""

    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""
    marketing_bundle_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'marketing_bundle.marketing_bundle_id',
        },
    )
    """Marketing bundle side of the relationship."""
    quantity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The quantity of the item in the marketing bundle."""
    release_time: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The time the marketing bundle was released as a UTC timestamp."""
