# generated by datamodel-codegen:
#   filename:  metagame_event.yaml
#   timestamp: 2025-11-27T09:24:04+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class MetagameEvent(RESTPayload):
    """In-game alerts and other alert-like events.

    Note that this endpoint lists alert types that may not be
    currently enabled in-game, such as the 'Aerial Anomaly' and
    'MAXimum Pressure' alert types."""

    description: LocalizedString | None = None
    """Description of the alert."""
    duration_minutes: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Duration of the event in minutes."""
    experience_bonus: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The experience bonus applied during the alert in percent."""
    metagame_event_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    name: LocalizedString | None = None
    """Display name of the alert."""
    type: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The type of the alert."""
