# generated by datamodel-codegen:
#   filename:  metagame_event_state.yaml
#   timestamp: 2025-11-27T09:24:07+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class MetagameEventState(RESTPayload):
    """Enumeratess the available states for alerts."""

    metagame_event_state_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    name: str
    """Internal name of the event state."""
