# generated by datamodel-codegen:
#   filename:  objective.yaml
#   timestamp: 2025-11-27T09:24:10+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Objective(RESTPayload):
    """An objective tracking progress towards a directive, mission, or
    achievement.

    See the `objective_type` collection for a list of available
    objective types."""

    objective_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unknown. This field allows connecting objectives to directives
    via the `ps2/objective_set_to_objective` collection."""
    objective_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    objective_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'objective_type.objective_type_id',
        },
    )
    """The `ps2/objective_type` of the objective."""
    param1: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param2: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param3: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param4: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param5: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param6: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param7: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param8: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
    param9: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/objective_type` for details."""
