# generated by datamodel-codegen:
#   filename:  objective_set_to_objective.yaml
#   timestamp: 2025-11-27T09:24:14+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ObjectiveSetToObjective(RESTPayload):
    """Maps objective sets to objective groups.

    This collection is peculiar as neither of the types it connects
    are available on the API. It is however essential for connecting
    the `directive` collection to `objective` and `objective_type`.

    Note that when joining to these queries, the `^on:` and `^to:`
    fields must be used to specify the relationship."""

    objective_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Objective group side of the relationship."""
    objective_set_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Objective set side of the relationship."""
