# generated by datamodel-codegen:
#   filename:  objective_type.yaml
#   timestamp: 2025-11-27T09:24:16+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ObjectiveType(RESTPayload):
    """A type of objective.

    The generic `paramX` fields are documented here. Note that not
    all fields are used by all objective types, or at all."""

    description: str
    """The description of the objective type."""
    objective_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    param1: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param2: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param3: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param4: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param5: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param6: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param7: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param8: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
    param9: str | None = None
    """Documentation for this numeric parameter on objectives of this
    type."""
