# generated by datamodel-codegen:
#   filename:  outfit_rank.yaml
#   timestamp: 2025-11-27T09:24:29+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class OutfitRank(RESTPayload):
    """Outfits can define their own custom rank names and permissions,
    which are listed here. Outfits using the default rank names may
    not have an entry here."""

    description: str | None = None
    """Custom description of the rank."""
    name: str | None = None
    """Custom name of the rank."""
    ordinal: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Ordinal of the rank. Lower values are higher ranks."""
    outfit_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int64', 'x-reference-to': 'outfit.outfit_id'},
    )
    """The `ps2/outfit` the rank belongs to."""
