# generated by datamodel-codegen:
#   filename:  outfit.yaml
#   timestamp: 2025-11-27T09:24:19+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Outfit(RESTPayload):
    """A player-run outfit (guild/clan) in the game."""

    alias: str | None = None
    """The outfit's alias (aka. tag), or an empty string if the outfit
    has no alias."""
    alias_lower: str | None = None
    """Lowercase version of `alias`."""
    leader_character_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The `ps2/character` of the outfit's leader."""
    member_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of members in the outfit."""
    name: str | None = None
    """Canonical name of the outfit."""
    name_lower: str | None = None
    """Lowercase version of `name`."""
    outfit_id: int = Field(..., json_schema_extra={'x-cast-to': 'int64'})
    """Unique ID of the collection."""
    time_created: str | None = None
    """Time the outfit was created."""
    time_created_date: str | None = None
    """Human-readable version of `time_created`."""
