# generated by datamodel-codegen:
#   filename:  outfit_member.yaml
#   timestamp: 2025-11-27T09:24:23+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class OutfitMember(RESTPayload):
    """Outfit membership information for a givne character. Characters
    that are not members of any outfit will not have an entry in this
    collection."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The `ps2/character` for this membership entry."""
    member_since: str | None = None
    """Time the character joined the outfit."""
    member_since_date: str | None = None
    """Human-readable version of `member_since`."""
    outfit_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int64', 'x-reference-to': 'outfit.outfit_id'},
    )
    """The `ps2/outfit` the character is a member of."""
    rank: str | None = None
    """Custom rank of the character in the outfit."""
    rank_ordinal: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Ordinal of the character's rank in the outfit. Lower values are
    higher ranks."""
