# generated by datamodel-codegen:
#   filename:  outfit_member_extended.yaml
#   timestamp: 2025-11-27T09:24:26+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class OutfitMemberExtended(RESTPayload):
    """Another variant of the `outfit_member` collection, but with the
    contents of the corresponding `outfit` merged in. This is useful
    for bulk lookups of outfit information for heterogenous lists of
    characters without requiring the explicit use of `c:join` or
    `c:resolve`."""

    alias: str | None = None
    """The outfit's alias (aka. tag), or an empty string if the outfit
    has no alias."""
    alias_lower: str | None = None
    """Lowercase version of `alias`."""
    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The `ps2/character` for this membership entry."""
    leader_character_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """The `ps2/character` of the outfit's leader."""
    member_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of members in the outfit."""
    member_rank: str | None = None
    """Custom rank of the character in the outfit."""
    member_rank_ordinal: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Ordinal of the character's rank in the outfit. Lower values are
    higher ranks."""
    member_since: str | None = None
    """Time the character joined the outfit."""
    member_since_date: str | None = None
    """Human-readable version of `member_since`."""
    name: str | None = None
    """Canonical name of the outfit."""
    name_lower: str | None = None
    """Lowercase version of `name`."""
    outfit_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int64', 'x-reference-to': 'outfit.outfit_id'},
    )
    """The `ps2/outfit` the character is a member of."""
    time_created: str | None = None
    """Time the outfit was created."""
    time_created_date: str | None = None
    """Human-readable version of `time_created`."""
