# generated by datamodel-codegen:
#   filename:  player_state_group.yaml
#   timestamp: 2025-11-27T09:24:35+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class PlayerStateGroup(RESTPayload):
    player_state_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Player state group to which this entry applies. Not unique."""
    player_state: str | None = None
    """Name of the player state for this entry."""
    min_cone_of_fire: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Minimum cone of fire for this player state in degrees."""
