# generated by datamodel-codegen:
#   filename:  player_state.yaml
#   timestamp: 2025-11-27T09:24:32+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class PlayerState(RESTPayload):
    player_state_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the player state."""
    description: str
    """Name of the player state."""
