# generated by datamodel-codegen:
#   filename:  player_state_group_2.yaml
#   timestamp: 2025-11-27T09:24:38+00:00

from typing import Any

from auraxium.models.base import RESTPayload
from pydantic import Field


class PlayerStateGroup2(RESTPayload):
    player_state_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the player state group."""
    player_state_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'player_state.player_state_id',
        },
    )
    """Player state ID enum value."""
    can_iron_sight: bool | None = Field(None, json_schema_extra={'x-cast-to': 'bool'})
    """Whether the player is allowed to enter aim-down-sights (ADS) in
    this state (0 or 1)."""
    cof_grow_rate: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Cone of fire growth per shot."""
    cof_max: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Maximum cone of fire."""
    cof_min: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Minimum cone of fire."""
    cof_recovery_delay_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Time before the cone-of-fire will start to reset after the user
    stopped firing."""
    cof_recovery_rate: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """CoThe speed at which the cone-of-fire will return to its starting
    value after the user stopped firing."""
    cof_shots_before_penalty: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Number of "free shots" before cone of fire penalty is applied."""
    cof_recovery_delay_threshold: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """(Not yet documented)"""
    cof_turn_penalty: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """(Not yet documented)"""
