# generated by datamodel-codegen:
#   filename:  profile_resist_map.yaml
#   timestamp: 2025-11-27T09:24:51+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ProfileResistMap(RESTPayload):
    """Maps profiles to the relevant `resist_info` entries. Note that
    many of the profile IDs used here are only available in the
    `profile_2` collection."""

    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """The profile side of the relationship."""
    rank: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unknown."""
    resist_info_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'resist_info.resist_info_id',
        },
    )
    """The resist info side of the relationship."""
