# generated by datamodel-codegen:
#   filename:  profile.yaml
#   timestamp: 2025-11-27T09:24:41+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Profile(RESTPayload):
    """Original endpoint for infantry profiles. This covers the names
    and loadout IDs connected to a given profile, and additionally
    provides movement speed multiplier information for infantry
    classes. Note that the key fields are also provided by
    `profile_2`, which not only covers infantry but also vehicles,
    deployables, and other entities."""

    backpedal_speed_modifier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """The modifier applied to the movement speed when walking
    backwards."""
    crouch_speed_modifier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """The modifier applied to the movement speed when crouching."""
    description: LocalizedString | None = None
    """Localized description of the profile"""
    faction_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """The `ps2/faction` of the profile."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """The `ps2/image` of the profile."""
    image_path: str | None = None
    """Relative path to the default image of the profile."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """The `ps2/image_set` of the profile."""
    movement_speed: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """The base movement speed of the profile."""
    name: LocalizedString | None = None
    """Localized name of the profile"""
    profile_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    profile_type_description: str | None = None
    """Internal description for the associated `profile_type_id`."""
    profile_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """The type of the profile. There is no public `profile_type`
    collection, this is an internal ID."""
    sprint_speed_modifier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """The modifier applied to the movement speed when sprinting."""
    strafe_speed_modifier: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """The modifier applied to the movement speed when strafing."""
