# generated by datamodel-codegen:
#   filename:  profile_armor_map.yaml
#   timestamp: 2025-11-27T09:24:48+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ProfileArmorMap(RESTPayload):
    """Maps profiles to the relevant `armor_info` entries.

    Note that many of the IDs used here are only available in
    `profile_2`. Additionally, armor values only concern vehicles,
    with infantry and deployable classes not having any entries here."""

    armor_info_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'armor_info.armor_info_id',
        },
    )
    """The armor info side of the relationship."""
    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """The profile side of the relationship."""
    rank: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unknown. Always 1 as of 2023-06-09."""
