# generated by datamodel-codegen:
#   filename:  profile_2.yaml
#   timestamp: 2025-11-27T09:24:45+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Profile2(RESTPayload):
    """Extended profile endpoint containing all entity types, including
    NPCs, construction items, and deployables."""

    description: str
    """Internal description of this profile. Not localized or user-
    facing."""
    profile_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection. Note that this is one of the few
    collections where the ID field is not `<collection>_id`."""
