# generated by datamodel-codegen:
#   filename:  projectile.yaml
#   timestamp: 2025-11-27T09:24:54+00:00

from typing import Any

from auraxium.models.base import RESTPayload
from pydantic import Field


class Projectile(RESTPayload):
    """Projectiles specify the travel characteristics of a weapon on its
    way to the target, such as its speed, its bullet drop, or maximum
    flight time/distance.

    Note that multiple fire modes can use the same projectile. This
    usually includes the hipfire vs. aimed fire modes, but can also
    include different weapons altogether."""

    acceleration: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """The acceleration of the projectile in metres per second per
    second. If NULL, the projectile will not accelerate and retain
    its initial speed."""
    arm_distance: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Minimum travel distance before the projectile is armed and can
    detonate. Used for Flak and Archer explosions."""
    detonate_distance: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Proximity required for Flak detonation."""
    detonate_on_contact: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether the projectile will detonate on contact with a surface or
    player."""
    drag: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    gravity: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Gravity applied to the projectile in metres per second per
    second. Togther with the current `speed`, this can be used to
    calculate bullet drop over time."""
    lifespan: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Lifespan of the projectile in seconds. Together with `speed`,
    `acceleration`, and `speed_max`, this can be used to calculate
    the maximum range of a given projectile."""
    lockon_acceleration: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Acceleration of the projectile while locked onto a target."""
    lockon_lifespan: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Duration of the lock-on effect in seconds. After this time, the
    lock will be lost."""
    lockon_lose_angle: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Field of view of the projectile when tracking a target. If the
    target escapes this cone, the lock is lost."""
    lockon_proximity_distance: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Distance at which the projectile will proximity-lock onto a
    target while in flight. Note that this value designates the
    diameter of the sphere of influence, not the radius."""
    lockon_seek_in_flight: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether a dumb-fired projectile will attempt to lock onto targets
    in flight. Used by the Coyote and Hyena missile launchers."""
    projectile_flight_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'projectile_flight_type.projectile_flight_type_id',
        },
    )
    """The `ps2/projectile_flight_type` of the projectile."""
    projectile_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the projectile."""
    projectile_radius: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """The radius of the projectile in metres. Relevant to hitbox
    collisions."""
    speed: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The initial speed of the projectile upon firing in meters per
    second. Note that this may be different from the muzzle velocity
    displayed for a given weapon."""
    speed_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Upper bound of the speed of the projectile in meters per second.
    On projectiles with a non-NULL `acceleration`, this is the top
    speed the projectile will reach."""
    sticks_to_players: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether the projectile will stick to infantry on contact. Note
    that in addition to Sticky Grenades, this will also be true for
    projectiles that only stick to MAXes, such as Nano-Repair or
    Anti-Vehicle Grenades."""
    sticky: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether the projectile will stick to surfaces. This includes
    Sticky Grenades and bricks of C-4 explosives."""
    tether_distance: Any | None = None
    turn_rate: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Turn rate of the projectile in degrees per second. Used to limit
    the ability of lock-on projectiles to track their target."""
