# generated by datamodel-codegen:
#   filename:  projectile_flight_type.yaml
#   timestamp: 2025-11-27T09:24:57+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ProjectileFlightType(RESTPayload):
    """Enumerates the flight types used to categorize projectiles by
    their travel characteristics.

    This mostly controls whether the projectile is ballistic, Flak-
    based, or "Dynamic", used to represent thrown items such as
    grenades, explosives, and ammo packs."""

    description: str = Field(..., json_schema_extra={'x-cast-to': 'string'})
    """Description of the projectile flight type."""
    projectile_flight_type_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32'}
    )
    """Unique ID of the collection."""
