# generated by datamodel-codegen:
#   filename:  region.yaml
#   timestamp: 2025-11-27T09:25:00+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Region(RESTPayload):
    """Display name of the game regions.

    This endpoint mostly contains the localized display name of the a
    map region. Regions and map regions are interchangeable and
    governed by the same IDs."""

    initial_faction_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """Defunct field. No longer applicable as warpgates are rotated on
    zone unlock."""
    name: LocalizedString | None = None
    """Name of the region."""
    region_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """ID of the zone in which the region is located."""
