# generated by datamodel-codegen:
#   filename:  resist_info.yaml
#   timestamp: 2025-11-27T09:25:03+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ResistInfo(RESTPayload):
    """Lists resistances against certain types of damage."""

    description: str | None = Field(None, json_schema_extra={'x-cast-to': 'string'})
    """Description of the resist info entry."""
    multiplier_when_headshot: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Headshot multiplier for this resistance."""
    resist_info_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    resist_percent: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Percentage of damage resisted. Negative numbers increase damage.
    Note that resistances can be greater than 100% to compensate for
    extra damage from relevant `armor_info` entries."""
    resist_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'resist_type.resist_type_id',
        },
    )
    """Resist type associated with this resist info entry."""
