# generated by datamodel-codegen:
#   filename:  resist_type.yaml
#   timestamp: 2025-11-27T09:25:06+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ResistType(RESTPayload):
    """Enumeration of resistance types used to balance damage types
    against various targets."""

    description: str = Field(..., json_schema_extra={'x-cast-to': 'string'})
    """Description of the resist type."""
    resist_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
