# generated by datamodel-codegen:
#   filename:  resource_type.yaml
#   timestamp: 2025-11-27T09:25:09+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ResourceType(RESTPayload):
    """Resources consumed by abilities such as the Heavy Overshield."""

    description: str = Field(..., json_schema_extra={'x-cast-to': 'string'})
    """Description of the resource type."""
    resource_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
