# generated by datamodel-codegen:
#   filename:  reward_group_to_reward.yaml
#   timestamp: 2025-11-27T09:25:15+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class RewardGroupToReward(RESTPayload):
    """Maps a reward group to one or more rewards.

    This collection, together with `reward_set_to_reward_group`,
    allows connecting directive tiers to the rewards they grant upon
    completion."""

    reward_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Reward group associated with this reward."""
    reward_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'reward.reward_id'},
    )
    """Reward associated with this reward group."""
