# generated by datamodel-codegen:
#   filename:  reward.yaml
#   timestamp: 2025-11-27T09:25:12+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Reward(RESTPayload):
    """A reward granted for completing a directive, mission, or
    achievement."""

    count_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Maximum number of items rewarded."""
    count_min: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Minimum number of items rewarded."""
    param1: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/reward_type` for details."""
    param2: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/reward_type` for details."""
    param3: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/reward_type` for details."""
    param4: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/reward_type` for details."""
    param5: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/reward_type` for details."""
    reward_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    reward_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'reward_type.reward_type_id',
        },
    )
    """Reward type associated with this reward."""
