# generated by datamodel-codegen:
#   filename:  reward_type.yaml
#   timestamp: 2025-11-27T09:25:20+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class RewardType(RESTPayload):
    """A type of reward.

    The generic `paramX` fields are documented here. Note that not
    all fields are used by all reward types, or at all."""

    count_max: str | None = None
    """Documentation for this parameter on rewards of this type."""
    count_min: str | None = None
    """Documentation for this parameter on rewards of this type."""
    description: str
    """Description of the reward type."""
    param1: str | None = None
    """Documentation for this numeric parameter on rewards of this type."""
    param2: str | None = None
    """Documentation for this numeric parameter on rewards of this type."""
    param3: str | None = None
    """Documentation for this numeric parameter on rewards of this type."""
    param4: str | None = None
    """Documentation for this numeric parameter on rewards of this type."""
    param5: str | None = None
    """Documentation for this numeric parameter on rewards of this type."""
    reward_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
