# generated by datamodel-codegen:
#   filename:  reward_set_to_reward_group.yaml
#   timestamp: 2025-11-27T09:25:18+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class RewardSetToRewardGroup(RESTPayload):
    """Maps a reward set to its reward group.

    This collection, together with `reward_group_to_reward`, allows
    connecting directive tiers to the rewards they grant upon
    completion."""

    reward_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Reward group associated with this reward set."""
    reward_set_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Reward set associated with this reward group."""
