# generated by datamodel-codegen:
#   filename:  single_character_by_id.yaml
#   timestamp: 2025-11-27T09:25:24+00:00

from typing import List

from auraxium.models.base import RESTPayload
from pydantic import Field


class BattleRank(RESTPayload):
    """Sub-object providing battle rank information."""

    percent_to_next: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Progress to the next level-up."""
    value: str | None = None
    """Current battle rank. Note that due to the A.S.P. prestige system,
    this is no longer sufficient to express player level. Always
    check `prestige_level` as well."""


class Certs(RESTPayload):
    """Sub-object providing certification point information."""

    available_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Current certification point balance."""
    earned_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Certifications earned through experience gain."""
    gifted_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Certifications gifted through in-game events or refunds."""
    percent_to_next: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """Progress to earning the next certification point (every 250 exp)."""
    spent_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Certifications points spent on skills and implant bundles."""


class DailyRibbon(RESTPayload):
    """Sub-object for daily ribbon bonuses. Note that ribbon bonuses
    have been disabled, rendering this object useless. It is
    recommended to treat is as optional in client code in case it
    ever gets removed from the response object."""

    count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of daily ribbon bonuses available for collection."""
    date: str | None = None
    """Human-readable version of `time`."""
    time: str | None = None
    """Next time a daily ribbon bonus will be granted."""


class Name(RESTPayload):
    """Name of the character. Use the `first_lower` field for faster
    case-insensitive searches without needing to set `c:case=false`."""

    first: str | None = None
    first_lower: str | None = None


class Times(RESTPayload):
    """Sub-object providing login time and playtime information."""

    creation: str | None = None
    """Character creation timestamp in UTC."""
    creation_date: str | None = None
    """Human-readable version of `creation`."""
    last_login: str | None = None
    """Last time the character logged in. Together with `last_save`,
    this can be used to construct the duration of the last play
    session of the character."""
    last_login_date: str | None = None
    """Human-readable version of `last_login`."""
    last_save: str | None = None
    """Last time the character info was updated. This generally
    corresponds to the last time the character logged off. For this
    reason, characters are generally not available on the API during
    their first play session."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    login_count: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of individual logins by the character."""
    minutes_played: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Total playtime in minutes."""


class Character(RESTPayload):
    """Main `character` collection holding player data.

    This collection is randomly distributed across 20 different
    databases, causing some unusual behaviour when filtering. For
    example, the `c:distinct` parameter will fetch the distinct
    values for each database and aggregate them in the response,
    resulting in duplicate entries.

    In addition to the commonly-used parameters provided, this
    endpoint may be queried by any of its fields, including sub-keys
    like `times.creation`."""

    battle_rank: BattleRank | None = None
    """Sub-object providing battle rank information."""
    certs: Certs | None = None
    """Sub-object providing certification point information."""
    character_id: int = Field(..., json_schema_extra={'x-cast-to': 'int64'})
    """Unique ID of the collection."""
    daily_ribbon: DailyRibbon | None = None
    """Sub-object for daily ribbon bonuses. Note that ribbon bonuses
    have been disabled, rendering this object useless. It is
    recommended to treat is as optional in client code in case it
    ever gets removed from the response object."""
    faction_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """Faction of the character. For NSOs, this equals the value of
    NSOs. An NSOs currently or home faction is not exposed on the
    REST API, but can be determined via the `team_id` of some
    WebSocket payloads."""
    head_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Identifier for the character's in-game model. Note that with
    gender change tokens, this is no longer guaranteed to be
    immutable across a character's career."""
    name: Name | None = None
    """Name of the character. Use the `first_lower` field for faster
    case-insensitive searches without needing to set `c:case=false`."""
    prestige_level: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The A.S.P. rank of the character."""
    profile_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class of the character when the last logged off. This value can
    generally only be one of the 24 infantry classes available in the
    legacy `ps2/profile` collection, though other values are possible
    due to bad data or deleted characters."""
    times: Times | None = None
    """Sub-object providing login time and playtime information."""
    title_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'title.title_id'},
    )
    """Currently selected title of the character. Useful for playing
    long names of players, e.g. "Snowblower Higby". A title ID of `0`
    corresponds to a player having selected "No Title" in-game."""


class CharactersCurrencyCore(RESTPayload):
    currency_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'currency.currency_id',
        },
    )
    """Unique ID of the currency being returned."""
    currency_name: str | None = None
    """Internal name of the currency being returned."""
    prestige_currency: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Number of A.S.P. tokens available to the character."""
    quantity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Amount of currency the character owns."""


class CharactersItemCore(RESTPayload):
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""


class CharactersStatCore(RESTPayload):
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    profile_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class for which stats are being returne."""
    stat_name: str
    """Name of the stat being returned."""
    value_daily: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours."""
    value_forever: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat."""
    value_monthly: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days."""
    value_one_life_max: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life."""
    value_weekly: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days."""


class CharactersStatByFactionCore(RESTPayload):
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    profile_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'profile_2.profile_id',
        },
    )
    """Class for which stats are being returne."""
    stat_name: str
    """Name of the stat being returned."""
    value_daily_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours (NC)."""
    value_daily_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours (TR)."""
    value_daily_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 24 hours (VS)."""
    value_forever_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat (NC)."""
    value_forever_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat (TR)."""
    value_forever_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat (VS)."""
    value_monthly_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days (NC)."""
    value_monthly_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days (TR)."""
    value_monthly_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 30 days (VS)."""
    value_one_life_max_nc: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life (NC)."""
    value_one_life_max_tr: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life (TR)."""
    value_one_life_max_vs: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Highest value of the stat in a single life (VS)."""
    value_weekly_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days (NC)."""
    value_weekly_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days (TR)."""
    value_weekly_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Value of the stat for the last 7 days (VS)."""


class Day(RESTPayload):
    d01: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d02: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d03: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d04: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d05: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d06: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d07: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d08: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d09: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d10: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d11: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d12: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d13: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d14: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d15: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d16: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d17: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d18: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d19: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d20: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d21: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d22: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d23: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d24: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d25: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d26: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d27: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d28: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d29: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d30: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d31: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})


class Month(RESTPayload):
    m01: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m02: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m03: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m04: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m05: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m06: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m07: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m08: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m09: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m10: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m11: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m12: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})


class Week(RESTPayload):
    w01: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w02: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w03: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w04: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w05: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})


class CharactersStatHistoryCore(RESTPayload):
    all_time: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """All-time value of the stat."""
    day: Day | None = None
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    month: Month | None = None
    one_life_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Highest value of the stat in a single life."""
    week: Week | None = None


class CharactersWeaponStatCore(RESTPayload):
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The ID of the item."""
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    stat_name: str = Field(
        ..., json_schema_extra={'x-reference-to': 'characters_stat.stat_name'}
    )
    """The name of the stat being recorded."""
    value: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat."""
    vehicle_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """The ID of the vehicle."""


class CharactersWeaponStatByFactionCore(RESTPayload):
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The ID of the item."""
    last_save: str | None = None
    """Last time the stat was saved."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    stat_name: str = Field(
        ..., json_schema_extra={'x-reference-to': 'characters_stat.stat_name'}
    )
    """The name of the stat being recorded."""
    value_nc: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat for the NC faction."""
    value_tr: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat for the TR faction."""
    value_vs: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The all-time value of the given stat for the VS faction."""
    vehicle_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """The ID of the vehicle."""


class StatHistory(RESTPayload):
    battle_rank: CharactersStatHistoryCore | None = None
    certs: CharactersStatHistoryCore | None = None
    deaths: CharactersStatHistoryCore | None = None
    facility_capture: CharactersStatHistoryCore | None = None
    facility_defend: CharactersStatHistoryCore | None = None
    kills: CharactersStatHistoryCore | None = None
    medals: CharactersStatHistoryCore | None = None
    ribbons: CharactersStatHistoryCore | None = None
    score: CharactersStatHistoryCore | None = None
    time: CharactersStatHistoryCore | None = None


class Stats(RESTPayload):
    stat: List[CharactersStatCore] | None = None
    stat_by_faction: List[CharactersStatByFactionCore] | None = None
    stat_history: StatHistory | None = None
    weapon_stat: List[CharactersWeaponStatCore] | None = None
    weapon_stat_by_faction: List[CharactersWeaponStatByFactionCore] | None = None


class CharactersItem(CharactersItemCore):
    """Query the items of a character. Note that this collection no
    longer lists account-wide item unlocks as this served as a
    fingerprint to identify players across multiple characters."""

    character_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int64',
            'x-reference-to': 'character.character_id',
        },
    )
    """Character side of the relationship."""
    item_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item side of the relationship."""


class SingleCharacterById(Character):
    """Endpoint for retrieving bulk character stats.

    This endpoint's payload is a superset of `character` and
    additionally includes data from
    related `characters_*` collections:

    - `characters_currency`
    - `characters_stat_history`
    - `characters_stat`
    - `characters_stat_by_faction`
    - `characters_weapon_stat`
    - `characters_weapon_stat_by_faction`
    - `characters_items`

    This endpoint is generally faster than querying these collections
    individually, but it
    comes with significant bandwidth costs. Note that this endpoint
    does not support most query
    commands, and that `c:show` and `c:hide` cannot be used to reduce
    the amount of data
    returned."""

    currency: CharactersCurrencyCore | None = None
    items: List[CharactersItem] | None = None
    stats: Stats | None = None
    character_id: int = Field(..., json_schema_extra={'x-cast-to': 'int64'})
    """Unique ID of the collection."""
