# generated by datamodel-codegen:
#   filename:  skill_line.yaml
#   timestamp: 2025-11-27T09:25:34+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class SkillLine(RESTPayload):
    """Skill lines represent upgrade paths for skills, such as Ammo
    Capacity."""

    description: LocalizedString | None = None
    """Description of the skill line."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Image associated with this skill line."""
    image_path: str | None = Field(None, json_schema_extra={'x-cast-to': 'string'})
    """Path to the image associated with this skill line."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Image set associated with this skill line."""
    name: LocalizedString | None = None
    """Display name of the skill line."""
    skill_category_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'skill_category.skill_category_id',
        },
    )
    """Skill category containing this skill line."""
    skill_category_index: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Position of this skill line within its skill category."""
    skill_line_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    skill_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unused."""
