# generated by datamodel-codegen:
#   filename:  skill_category.yaml
#   timestamp: 2025-11-27T09:25:31+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class SkillCategory(RESTPayload):
    """Skill categories represent a grouping of skills.

    They usually group skills by the loadout slots for which they
    provide items, such as "Passive Systems" or "Ability Slot". On
    weapons, they generally represent a given attachment slot."""

    description: LocalizedString | None = None
    """Description of the skill category."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Image associated with this skill category."""
    image_path: str | None = Field(None, json_schema_extra={'x-cast-to': 'string'})
    """Path to the image associated with this skill category."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Image set associated with this skill category."""
    name: LocalizedString | None = None
    """Display name of the skill category."""
    skill_category_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    skill_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unused."""
    skill_set_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'skill_set.skill_set_id',
        },
    )
    """Skill set containing this skill category."""
    skill_set_index: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Position of this skill category within its skill set."""
