# generated by datamodel-codegen:
#   filename:  skill.yaml
#   timestamp: 2025-11-27T09:25:27+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Skill(RESTPayload):
    """Purchasable skills, such as certifications and A.S.P. skills."""

    description: LocalizedString | None = None
    """Description of the skill."""
    grant_item_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Item granted by this skill. The skill must be unlocked for the
    item to be available in the player's loadouts."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Image associated with this skill."""
    image_path: str | None = Field(None, json_schema_extra={'x-cast-to': 'string'})
    """Path to the image associated with this skill."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Image set associated with this skill."""
    name: LocalizedString | None = None
    """Display name of the skill."""
    skill_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    skill_line_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'skill_line.skill_line_id',
        },
    )
    """Skill line containing this skill."""
    skill_line_index: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Position of this skill for upgradable skill lines such as Ammo
    Capacity."""
    skill_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of skill points (Certs or A.S.P. tokens) required to
    unlock this skill."""
