# generated by datamodel-codegen:
#   filename:  skill_set.yaml
#   timestamp: 2025-11-27T09:25:37+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class SkillSet(RESTPayload):
    """Skill sets represent the top-level grouping of skills.

    In the old certification menu, this would group weapon-related
    skill lines into a sub-tree beneath the weapon itself."""

    description: LocalizedString | None = None
    """Description of the skill set."""
    image_id: int | None = Field(
        None,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'image.image_id'},
    )
    """Image associated with this skill set."""
    image_path: str | None = Field(None, json_schema_extra={'x-cast-to': 'string'})
    """Path to the image associated with this skill set."""
    image_set_id: int | None = Field(
        None,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'image_set.image_set_id',
        },
    )
    """Image set associated with this skill set."""
    name: LocalizedString | None = None
    """Display name of the skill set."""
    required_item_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """The item associated with this skill set. Contained skill lines
    are only available once this item has been unlocked."""
    skill_points: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unlock cost of the skill set. For weapon skill sets, this is
    equal to the certification cost of the weapon item."""
    skill_set_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
