# generated by datamodel-codegen:
#   filename:  target_type.yaml
#   timestamp: 2025-11-27T09:25:40+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class TargetType(RESTPayload):
    """Enumerates the target types used to categorize the applicable
    targets of a weapon or effect.

    This is effectively a constant mapping and can be cached
    aggressively."""

    description: str = Field(..., json_schema_extra={'x-cast-to': 'string'})
    """Description of the target type."""
    target_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
