# generated by datamodel-codegen:
#   filename:  title.yaml
#   timestamp: 2025-11-27T09:25:42+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Title(RESTPayload):
    """Selectable titles for a character.

    Note that title IDs of 0 signify no title being selected."""

    name: LocalizedString | None = None
    """Display name of the title."""
    title_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
