# generated by datamodel-codegen:
#   filename:  vehicle.yaml
#   timestamp: 2025-11-27T09:25:45+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Vehicle(RESTPayload):
    """Basic vehicle information such as name, description, and type.

    Note that vehicle types are only used internally and are not
    directly tied to damage mechanics or resistances. Liberators and
    Galaxies are still considered "Light Aircraft" in this endpoint."""

    cost: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Defunct field. Does not reflect the actual resource cost of the
    vehicle."""
    cost_resource_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the currency used to purchase the vehicle."""
    description: LocalizedString | None = None
    """Description of the vehicle."""
    image_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the default image for the vehicle icon."""
    image_path: str | None = Field(None, json_schema_extra={'x-cast-to': 'string'})
    """Path to the default image for the vehicle icon."""
    image_set_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the image set for the vehicle icon."""
    name: LocalizedString | None = None
    """Display name of the vehicle."""
    type_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the vehicle type. Note that vehicle types are not related
    to damage types; Liberators still qualify as "Light Aircraft"."""
    type_name: str | None = None
    """Internal name of the vehicle type. Note that vehicle types are
    not related to damage types; Liberators still qualify as "Light
    Aircraft"."""
    vehicle_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
