# generated by datamodel-codegen:
#   filename:  vehicle_skill_set.yaml
#   timestamp: 2025-11-27T09:25:53+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class VehicleSkillSet(RESTPayload):
    """Maps vehicles to the skill sets that they use.

    Note that this relationship is expressed for each faction
    separetly."""

    display_index: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Index used to sort the skill sets in the vehicle's UI."""
    faction_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """ID of the faction that can use the skill set."""
    skill_set_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'skill_set.skill_set_id',
        },
    )
    """Skill set side of the relationship."""
    vehicle_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """Vehicle side of the relationship."""
