# generated by datamodel-codegen:
#   filename:  vehicle_attachment.yaml
#   timestamp: 2025-11-27T09:25:48+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class VehicleAttachment(RESTPayload):
    """Maps items to the vehicles and factions that have access to them.

    The `slot_id` field is used to identify where the item is
    attached to. The below list shows
    the types of items for each slot as of June 2023:

    ```
    ID   Description

    1    Primary Weapon
    2    Secondary Weapon
    3    Ability Slot
    4    Defensive Slot
    5    Chassis / Airframe
    6    Cockpit / Hood Ornament
    7    Camo
    8    Decal
    9    Exterior
    10   Weapon Slot / Catapult
    11   Weapon Slot / Catapult
    12   Afterburner / Nitrous
    13   (Unused)
    14   (Internal: Headlights)
    15   Horn
    16   Trim
    17   Lighting
    18   Hubcaps
    19   Other
    20   Tire Traits / Catapult
    21   Catapult
    22   Catapult
    ```

    Note that this list is maintained manually and may be out of
    date. The slot associations
    are not available on the API."""

    description: str | None = None
    """Internal description of the vehicle/faction combination."""
    faction_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """ID of the faction that can use the attachment."""
    item_id: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'item.item_id'}
    )
    """Unique ID of the attachment item."""
    slot_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the slot the attachment occupies. See the
    `ps2/vehicle_attachment` endpoint documentation for a mapping of
    slot IDs to item types."""
    vehicle_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """Unique ID of the vehicle."""
