# generated by datamodel-codegen:
#   filename:  vehicle_faction.yaml
#   timestamp: 2025-11-27T09:25:51+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class VehicleFaction(RESTPayload):
    """Maps vehicles to the factions that have access to them."""

    faction_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'faction.faction_id',
        },
    )
    """ID of the faction that can use the vehicle."""
    vehicle_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'vehicle.vehicle_id',
        },
    )
    """Unique ID of the vehicle."""
