# generated by datamodel-codegen:
#   filename:  weapon_to_fire_group.yaml
#   timestamp: 2025-11-27T09:26:08+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class WeaponToFireGroup(RESTPayload):
    """Maps weapons to their set of fire groups. The `fire_group_index`
    field matches the in-game fire mode selection; hitting 'B' in-
    game is equivalent to incrementing the index by 1."""

    fire_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the fire group."""
    fire_group_index: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Index of the fire group in the weapon's fire group list."""
    weapon_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the weapon."""
