# generated by datamodel-codegen:
#   filename:  weapon_datasheet.yaml
#   timestamp: 2025-11-27T09:26:02+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class WeaponDatasheet(RESTPayload):
    """**Deprecated:** This table is not directly tied to the underlying
    fire mode and player state group data and may differ wildly from
    the true values!

    Suggested alternatives for the values provided by this collection
    are listed as part of the `weapon_datasheet` schema."""

    capacity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please refer to the matching `ps2/weapon_ammo_slot`
    instead."""
    clip_size: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please refer to the matching `ps2/weapon_ammo_slot`
    instead."""
    damage: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please use the values from `ps2/fire_mode_2` instead."""
    damage_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please use the values from `ps2/fire_mode_2` instead."""
    damage_min: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please use the values from `ps2/fire_mode_2` instead."""
    direct_damage: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please refer to the damage effect listed in
    `ps2/fire_mode_2.damage_direct_effect_id` instead."""
    fire_cone: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Unreliable! Please refer to the player state group listed in
    `ps2/fire_mode_2.player_state_group_id` instead."""
    fire_cone_max: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Unreliable! Please refer to the `cof_` values in
    `ps2/fire_mode_2` instead."""
    fire_cone_min: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Unreliable! Please refer to the player state group listed in
    `ps2/fire_mode_2.player_state_group_id` instead."""
    fire_rate_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please use `ps2/fire_mode_2.fire_refire_ms` instead."""
    fire_rate_mx_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please use `ps2/fire_mode_2.fire_refire_ms` instead.
    Note that this is not a typo in the spec, the field is named
    `mx`."""
    fire_rate_ms_min: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please use `ps2/fire_mode_2.fire_refire_ms` instead."""
    indirect_damage: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please refer to the damage effect listed in
    `ps2/fire_mode_2.damage_indirect_effect_id` instead."""
    item_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """ID of the item to which this datasheet belongs."""
    range: LocalizedString | None = None
    """Localized name of the displayed range of the weapon."""
    reload_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please add the values of
    `ps2/fire_mode_2.reload_time_ms` instead."""
    reload_ms_max: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please add the values of
    `ps2/fire_mode_2.reload_time_ms` and
    `ps2/fire_mode_2.reload_chamber_ms` together to get long reload
    time."""
    reload_ms_min: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Unreliable! Please add the values of
    `ps2/fire_mode_2.reload_time_ms` instead."""
    show_clip_size: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether the clip size should be displayed in the UI."""
    show_fire_modes: bool | None = Field(
        None, json_schema_extra={'x-cast-to': 'boolean'}
    )
    """Whether the fire modes (in-game interpretation of this term)
    should be displayed in the UI."""
    show_range: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether the range string should be displayed in the UI."""
