# generated by datamodel-codegen:
#   filename:  weapon.yaml
#   timestamp: 2025-11-27T09:25:56+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Weapon(RESTPayload):
    """Baseline weapon data, such as equip times, stock sights, and
    movement speed modifiers."""

    equip_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The time in milliseconds it takes to equip the weapon."""
    from_iron_sights_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Transition duration when exiting aim-down-sights in milliseconds."""
    heat_bleed_off_rate: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Rate at which heat is dissipated when not firing. Note that this
    value is represented as an integer on the API despite being a
    float internally."""
    heat_capacity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Total capacity for heat-based weapons. This is comparable to the
    magazine size of regular weapons."""
    heat_overheat_penalty_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """The time in milliseconds it takes for the weapon to start cooling
    down after overheating."""
    melee_detect_height: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """On melee weapons, designates the height of the quick knife attack
    hitbox."""
    melee_detect_width: float | None = Field(
        None, json_schema_extra={'x-cast-to': 'float'}
    )
    """On melee weapons, designates the width of the quick knife attack
    hitbox."""
    move_modifier: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """The modifier applied to the movement speed when the weapon is
    equipped."""
    requires_ammo: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether equipping this weapon requires ammunition to be
    available. Used for grenades or the medic's shield regen device
    to prevent selection when out of ammo."""
    sprint_recovery_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Time after sprinting during which the cone-of-fire will retain
    its sprinting value before starting to recover."""
    to_iron_sights_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Transition duration when entering aim-down-sights in
    milliseconds."""
    turn_modifier: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """The modifier applied to the turn speed when the weapon is
    equipped."""
    unequip_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The time in milliseconds it takes to unequip the weapon."""
    use_cooldown_ms: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Time in milliseconds between uses of this weapon."""
    weapon_group_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """ID of the weapon's group. Weapons in the same group are treated
    as a single weapon despite having distinct items. Examples
    include upgradable pseudo-weapons such as the medic or engineer
    tool, or the Infiltrator's Recon dart gun.
    
    Note that not all weapons have weapon groups, and that most
    weapon groups have only one weapon in them. The presence of this
    field has no bearing on the weapon being grouped or not."""
    weapon_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
