# generated by datamodel-codegen:
#   filename:  weapon_ammo_slot.yaml
#   timestamp: 2025-11-27T09:25:59+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class WeaponAmmoSlot(RESTPayload):
    """Ammo slot data for a given weapon, including the clip size,
    reserve ammo capacity, and resupply behaviour."""

    capacity: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Reserve ammunition capacity of this ammo slot."""
    clip_size: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """The number of bullets in a single clip of this ammo slot."""
    refill_ammo_delay_ms: int | None = Field(
        None, json_schema_extra={'x-cast-to': 'int32'}
    )
    """Extra cooldown between ammo resupply ticks. The base ammo
    resupply tick rate is not available on the API."""
    refill_ammo_rate: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Number of bullets refilled per ammo resupply tick."""
    weapon_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """ID of the weapon to which this ammo slot belongs."""
    weapon_slot_index: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Index of the slot in the weapon's ammo slot list."""
