# generated by datamodel-codegen:
#   filename:  weapon_to_attachment.yaml
#   timestamp: 2025-11-27T09:26:05+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class WeaponToAttachment(RESTPayload):
    """Maps weapons to the attachments available to them. This table is
    largely synonymous with `item_attachment`, but contains
    additional entries that may not resolve to a valid item.

    For this reason, it is recommended to base any attachment queries
    on the `item_attachment` endpoint instead."""

    attachment_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Internal ID of this mapping. Does not map to any other field in
    the API."""
    item_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the attachment item."""
    weapon_group_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """ID of the weapon group to which this item can be attached."""
