# generated by datamodel-codegen:
#   filename:  world_event.yaml
#   timestamp: 2025-11-27T09:26:13+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field, RootModel


class EventBase(RESTPayload):
    event_type: str
    """Name of the event."""
    table_type: str
    """Internal name of the table."""
    timestamp: str
    """UTC timestamp of the event."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""


class WorldEvent1(EventBase):
    """ReST endpoint for retrieving historical world events.

    The `world_id` and `id` fields are interchangeable."""

    duration_held: str | None = None
    """Time in seconds since the facility was held by the previous
    owner."""
    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    facility_id: str | None = None
    """The ID of the facility that was captured."""
    faction_new: str | None = None
    """The faction that owns the facility after the capture."""
    faction_old: str | None = None
    """The faction that owned the facility before the capture."""
    objective_id: str | None = None
    """Unknown."""
    outfit_id: str | None = None
    """Unique ID of the outfit that captured the facility."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""


class WorldEvent2(EventBase):
    """ReST endpoint for retrieving historical world events.

    The `world_id` and `id` fields are interchangeable."""

    event_type: str
    """Type of event. This generally matches the event types used by the
    ESS."""
    experience_bonus: str | None = None
    """Experience bonus for the winning faction."""
    faction_nc: str | None = None
    """Current scope of the NC faction."""
    faction_tr: str | None = None
    """Current scope of the TR faction."""
    faction_vs: str | None = None
    """Current scope of the VS faction."""
    instance_id: str | None = None
    """Unique ID of this particular instance of the metagame event. Only
    unique per server restart, not globally."""
    metagame_event_id: str | None = None
    """Unique ID of the metagame event."""
    metagame_event_state: str | None = None
    """Unique ID of the metagame event state."""
    metagame_event_state_name: str | None = None
    """Name of the metagame event state."""
    zone_id: int = Field(
        ..., json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'zone.zone_id'}
    )
    """The ID of the zone where the character ranked up."""
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """The ID of the world where the character ranked up."""


class WorldEvent(RootModel[WorldEvent1 | WorldEvent2]):
    root: WorldEvent1 | WorldEvent2
    """
    ReST endpoint for retrieving historical world events.

    The `world_id` and `id` fields are interchangeable.

    """
