# generated by datamodel-codegen:
#   filename:  world.yaml
#   timestamp: 2025-11-27T09:26:10+00:00

from enum import Enum

from auraxium.models.base import RESTPayload
from pydantic import Field


class State(Enum):
    """
    Current availability of the game server.
    """

    online = 'online'
    locked = 'locked'


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class World(RESTPayload):
    """A game server for a given region and game."""

    description: LocalizedString | None = None
    """Localized description set for some worlds. Unused for most."""
    name: LocalizedString | None = None
    """Localized name of the world"""
    state: State | None = None
    """Current availability of the game server."""
    world_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
