# generated by datamodel-codegen:
#   filename:  world_stat_history.yaml
#   timestamp: 2025-11-27T09:26:16+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class Day(RESTPayload):
    d01: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d02: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d03: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d04: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d05: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d06: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d07: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d08: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d09: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d10: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d11: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d12: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d13: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d14: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d15: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d16: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d17: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d18: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d19: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d20: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d21: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d22: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d23: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d24: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d25: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d26: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d27: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d28: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d29: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d30: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    d31: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})


class Month(RESTPayload):
    m01: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m02: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m03: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m04: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m05: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m06: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m07: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m08: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m09: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m10: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m11: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    m12: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})


class Week(RESTPayload):
    w01: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w02: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w03: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w04: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w05: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w06: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w07: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w08: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w09: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w10: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w11: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w12: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    w13: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})


class WorldStatHistory(RESTPayload):
    """Defunct. Historical data for global events."""

    all_time: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Total value of the stat for the given world, tracker and faction."""
    day: Day | None = None
    faction: str | None = None
    """Code for the faction for which the data is returned."""
    last_save: str | None = None
    """UTC timestamp of when the tracker was last updated."""
    last_save_date: str | None = None
    """Human-readable version of `last_save`."""
    month: Month | None = None
    stat_name: str = Field(..., json_schema_extra={'x-reference-to': 'stat.stat_name'})
    """Name of the stat for which the data is returned."""
    tracker_name: str | None = None
    """Name of the tracker for which the data is returned."""
    type: str | None = None
    """Type of the tracker for which the data is returned."""
    week: Week | None = None
    world_id: int = Field(
        ...,
        json_schema_extra={'x-cast-to': 'int32', 'x-reference-to': 'world.world_id'},
    )
    """Unique ID of the world for which the data is returned."""
