# generated by datamodel-codegen:
#   filename:  zone_effect_type.yaml
#   timestamp: 2025-11-27T09:26:25+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ZoneEffectType(RESTPayload):
    """A type of zone effect.

    The generic fields `paramX` and `stringX` are documented here.
    Note that not all fields are used by all zone effect types, or at
    all."""

    description: str
    """Description of the zone effect type."""
    param1: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param10: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param11: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param12: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param13: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param14: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param2: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param3: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param4: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param5: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param6: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param7: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param8: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    param9: str | None = None
    """Documentation for this numeric parameter on zone effects of this
    type."""
    string1: str | None = None
    """Documentation for this string parameter on zone effects of this
    type."""
    string2: str | None = None
    """Documentation for this string parameter on zone effects of this
    type."""
    string3: str | None = None
    """Documentation for this string parameter on zone effects of this
    type."""
    string4: str | None = None
    """Documentation for this string parameter on zone effects of this
    type."""
    zone_effect_type_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
