# generated by datamodel-codegen:
#   filename:  zone_effect.yaml
#   timestamp: 2025-11-27T09:26:22+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class ZoneEffect(RESTPayload):
    """Passive effects such as weapon stat modifications from
    attachments or equipped skills.

    For weapon damage effects, see `effect` instead. See the
    `zone_effect_type` collection for a list of available zone effect
    types."""

    ability_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'ability.ability_id',
        },
    )
    """Unique ID of the associated ability."""
    param1: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param10: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param11: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param12: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param13: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param14: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param2: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param3: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param4: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param5: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param6: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param7: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param8: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    param9: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Generic numeric parameter. See the corresponding
    `ps2/zone_effect_type` for details."""
    string1: str | None = None
    """Generic string field. See the corresponding
    `ps2/zone_effect_type` for details."""
    string2: str | None = None
    """Generic string field. See the corresponding
    `ps2/zone_effect_type` for details."""
    string3: str | None = None
    """Generic string field. See the corresponding
    `ps2/zone_effect_type` for details."""
    string4: str | None = None
    """Generic string field. See the corresponding
    `ps2/zone_effect_type` for details."""
    zone_effect_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
    zone_effect_type_id: int = Field(
        ...,
        json_schema_extra={
            'x-cast-to': 'int32',
            'x-reference-to': 'zone_effect_type.zone_effect_type_id',
        },
    )
    """Unique ID of the zone effect type."""
