# generated by datamodel-codegen:
#   filename:  zone.yaml
#   timestamp: 2025-11-27T09:26:19+00:00

from auraxium.models.base import RESTPayload
from pydantic import Field


class LocalizedString(RESTPayload):
    de: str | None = None
    """German locale"""
    en: str | None = None
    """English locale"""
    es: str | None = None
    """Spanish locale"""
    fr: str | None = None
    """French locale"""
    it: str | None = None
    """Italian locale"""
    tr: str | None = None
    """Turkish locale, unfinished and not available for most fields"""


class Zone(RESTPayload):
    """World continent and dynamic zone information."""

    code: str | None = None
    """Internal code of the zone. Used to connect map textures to the
    zone."""
    description: LocalizedString | None = None
    """Localized description of the zone"""
    dynamic: bool | None = Field(None, json_schema_extra={'x-cast-to': 'boolean'})
    """Whether this zone is dynamic or not. Multiple dynamic zones of
    the same `geometry_id` may exist for a given `ps2/world`, such as
    Sanctuary instances or Outfit Wars rooms."""
    geometry_id: int | None = Field(None, json_schema_extra={'x-cast-to': 'int32'})
    """Internal geometry ID of the zones with dynamic IDs. Prior to this
    field being added, this ID was referred to as `definition_id` by
    community developers."""
    hex_size: float | None = Field(None, json_schema_extra={'x-cast-to': 'float'})
    """Radius of a map hex in metres."""
    name: LocalizedString | None = None
    """Localized name of the zone"""
    zone_id: int = Field(..., json_schema_extra={'x-cast-to': 'int32'})
    """Unique ID of the collection."""
