version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
