# This workflow will run any files matching "tests/*_test.py" using the Python
# unittest module.

name: CI Testing

on: [push, pull_request]

jobs:
  offline-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r ./requirements.txt
      - name: Run unit tests
        run: |
          python -m unittest discover -p *_test.py tests/unit/
      - name: Run integration tests
        run: |
          python -m unittest discover -p *_test.py tests/integration/

  live-tests:
    runs-on: ubuntu-latest
    needs: offline-tests
    if: github.repository == 'leonhard-s/auraxium' && github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r ./requirements.txt

      - name: Run live tests
        env:
          SERVICE_ID: ${{secrets.REPO_SERVICE_ID}}
        run: |
          python -m unittest discover -p *_test.py tests/live/
