# This workflow runs the "live" test set once a day to detect API
# breakages.

name: Daily CI Tests

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'leonhard-s/auraxium'

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Run live tests
        env:
          SERVICE_ID: ${{secrets.REPO_SERVICE_ID}}
        run: |
          python -m unittest discover -p *_test.py tests/live/
